apiVersion: v1
kind: ServiceAccount
metadata:
  name: estela-api
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: estela-api-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "cronjobs", "jobs/status", "cronjobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: estela-api-bind
subjects:
- kind: ServiceAccount
  name: estela-api
  namespace: default
roleRef:
  kind: ClusterRole
  name: estela-api-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: estela-django-api
spec:
  selector:
    matchLabels:
      app: estela-django-api
  template:
    metadata:
      labels:
        app: estela-django-api
    spec:
      serviceAccountName: estela-api
      containers:
      - name: estela-django-api
        image: 192.168.49.1:5000/estela-django-api
        imagePullPolicy: Always
        command: ['gunicorn', 'config.wsgi', '--bind=0.0.0.0:8000']
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: estela-celery-beat
spec:
  selector:
    matchLabels:
      app: estela-celery-beat
  template:
    metadata:
      labels:
        app: estela-celery-beat
    spec:
      serviceAccountName: estela-api
      containers:
      - name: estela-celery-beat
        image: 192.168.49.1:5000/estela-celery-beat
        command: ['celery', '-A', 'config.celery', 'beat', '--loglevel=info']
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: estela-celery-worker
spec:
  selector:
    matchLabels:
      app: estela-celery-worker
  template:
    metadata:
      labels:
        app: estela-celery-worker
    spec:
      serviceAccountName: estela-api
      containers:
      - name: estela-celery-worker
        image: 192.168.49.1:5000/estela-celery-worker
        command: ['celery', '-A', 'config.celery', 'worker', '--loglevel=info']
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: default
  name: estela-redis
spec:
  selector:
    matchLabels:
      app: estela-redis
  template:
    metadata:
      labels:
        app: estela-redis
    spec:
      containers:
      - name: estela-redis
        image: 192.168.49.1:5000/estela-redis

