REGISTRY_HOST = <IPV4_ADDRESS:5000>
REGION = us-east-2
APIPOD = $$(kubectl get pod -l app=estela-django-api -o jsonpath="{.items[0].metadata.name}")
API_DOC = docs/api.yaml
DEVTAG = latest#dev-$$USER

ifeq ($(OS),Windows_NT)
	DOCKER_COMPOSE = docker compose
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		DOCKER_COMPOSE = docker-compose
	else # OSX
		DOCKER_COMPOSE = docker compose
	endif
endif

.PHONY: start
start:
	-minikube start --feature-gates="TTLAfterFinished=true" --insecure-registry $(REGISTRY_HOST)
	-$(DOCKER_COMPOSE) up -d


.PHONY: stop
stop:
	-minikube stop
	-$(DOCKER_COMPOSE) stop


.PHONY: setup
setup: build-api-image upload-api-image
	-kubectl apply -f config/kubernetes/estela-api-secrets.yaml
	-kubectl apply -f config/kubernetes/estela-api-services.yaml
	-kubectl apply -f config/kubernetes/estela-api-configmaps.yaml
	-kubectl apply -f config/kubernetes/aws-registry-cronjob.yaml
	-kubectl apply -f config/kubernetes/estela-filebeat.yaml
	-kubectl apply -f config/kubernetes/estela-api-deployments.yaml
	-kubectl set image deployment/estela-django-api estela-django-api=$(REGISTRY_HOST)/estela-django-api:$(DEVTAG)


.PHONY: rebuild-api
rebuild-api: build-api-image upload-api-image
	-kubectl apply -f config/kubernetes/estela-api-secrets.yaml
	-kubectl apply -f config/kubernetes/estela-api-configmaps.yaml
	-kubectl rollout restart deployment estela-django-api
	-kubectl set image deployment/estela-django-api estela-django-api=$(REGISTRY_HOST)/estela-django-api:$(DEVTAG)


.PHONY: rebuild-all
rebuild-all: build-all-images upload-all-images
	-kubectl apply -f config/kubernetes/estela-api-secrets.yaml
	-kubectl apply -f config/kubernetes/estela-api-configmaps.yaml
	-kubectl rollout restart deployment estela-django-api
	-kubectl set image deployment/estela-django-api estela-django-api=$(REGISTRY_HOST)/estela-django-api:$(DEVTAG)
	-kubectl rollout restart deployment estela-celery-worker
	-kubectl set image deployment/estela-celery-worker estela-celery-worker=$(REGISTRY_HOST)/estela-celery-worker:$(DEVTAG)
	-kubectl rollout restart deployment estela-celery-beat
	-kubectl set image deployment/estela-celery-beat estela-celery-beat=$(REGISTRY_HOST)/estela-celery-beat:$(DEVTAG)
	-kubectl rollout restart deployment estela-redis
	-kubectl set image deployment/estela-redis estela-redis=$(REGISTRY_HOST)/estela-redis:$(DEVTAG)


.PHONY: down
down:
	-kubectl delete -f config/kubernetes/estela-api-secrets.yaml
	-kubectl delete -f config/kubernetes/estela-api-configmaps.yaml
	-kubectl delete -f config/kubernetes/aws-registry-cronjob.yaml
	-kubectl delete -f config/kubernetes/estela-api-services.yaml
	-kubectl delete -f config/kubernetes/estela-api-deployments.yaml
	-kubectl delete jobs $$(kubectl get jobs -o custom-columns=:.metadata.name)
	-kubectl delete cronjobs $$(kubectl get cronjobs -o custom-columns=:.metadata.name)
	-minikube delete
	-$(DOCKER_COMPOSE) down


.PHONY: test
test:
	-kubectl exec $(APIPOD) -- pytest -svx


.PHONY: makemigrations
makemigrations:
	-kubectl exec $(APIPOD) -- python manage.py makemigrations


.PHONY: migrate
migrate:
	-kubectl exec $(APIPOD) -- python manage.py migrate


.PHONY: createsuperuser
createsuperuser:
	-kubectl exec --stdin --tty $(APIPOD) -- python manage.py createsuperuser


.PHONY: login-ecr
login-ecr:
	-aws ecr get-login-password --region $(REGION) | docker login \
	   --username AWS --password-stdin  $(REGISTRY_HOST)


.PHONY: build-all-images
build-all-images:
	-docker build .. --file docker-conf/Dockerfile-django-api --tag estela-django-api:$(DEVTAG)
	-docker build .. --file docker-conf/Dockerfile-celery-worker --tag estela-celery-worker:$(DEVTAG)
	-docker build .. --file docker-conf/Dockerfile-celery-beat --tag estela-celery-beat:$(DEVTAG)
	-docker build . --file docker-conf/Dockerfile-redis --tag estela-redis:$(DEVTAG)
	-docker build .. --file docker-conf/Dockerfile-build-project --tag estela-build-project:$(DEVTAG)


.PHONY: upload-all-images
upload-all-images: login-ecr
	-docker tag estela-django-api:$(DEVTAG) $(REGISTRY_HOST)/estela-django-api:$(DEVTAG)
	-docker tag estela-celery-beat:$(DEVTAG) $(REGISTRY_HOST)/estela-celery-beat:$(DEVTAG)
	-docker tag estela-celery-worker:$(DEVTAG) $(REGISTRY_HOST)/estela-celery-worker:$(DEVTAG)
	-docker tag estela-redis:$(DEVTAG) $(REGISTRY_HOST)/estela-redis:$(DEVTAG)
	-docker tag estela-build-project:$(DEVTAG) $(REGISTRY_HOST)/estela-build-project:$(DEVTAG)
	-docker push $(REGISTRY_HOST)/estela-django-api:$(DEVTAG)
	-docker push $(REGISTRY_HOST)/estela-celery-beat:$(DEVTAG)
	-docker push $(REGISTRY_HOST)/estela-celery-worker:$(DEVTAG)
	-docker push $(REGISTRY_HOST)/estela-redis:$(DEVTAG)
	-docker push $(REGISTRY_HOST)/estela-build-project:$(DEVTAG)


.PHONY: set-up-images
set-up-images: build-all-images upload-all-images


.PHONY: set-up-images
set-up-images: build-all-images upload-all-images


.PHONY: build-api-image
build-api-image:
	-docker build .. --file docker-conf/Dockerfile-django-api --tag estela-django-api:$(DEVTAG)


.PHONY: upload-api-image
upload-api-image: login-ecr
	-docker tag estela-django-api:$(DEVTAG) $(REGISTRY_HOST)/estela-django-api:$(DEVTAG)
	-docker push $(REGISTRY_HOST)/estela-django-api:$(DEVTAG)


.PHONY: docs
docs:
	-rm $(API_DOC)
	-python manage.py generate_swagger -f yaml $(API_DOC)


.PHONY: lint
lint:
	-black .
