apiVersion: v1
kind: ServiceAccount
metadata:
  name: bitmaker-api
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bitmaker-api-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch", "extensions"]
  resources: ["jobs", "cronjobs", "jobs/status", "cronjobs/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bitmaker-api-bind
subjects:
- kind: ServiceAccount
  name: bitmaker-api
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: bitmaker-api-role
  apiGroup: rbac.authorization.k8s.io