apiVersion: v1
kind: Service
metadata:
  name: bitmaker-django-api-service
  labels:
    app: bitmaker-django-api
spec:
  ports:
  - port: 80
    targetPort: 8000
    name: bitmaker-django-api-port
    protocol: TCP
  selector:
    app: bitmaker-django-api
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
---
kind: Endpoints
apiVersion: v1
metadata:
  name: database
subsets:
  - addresses:
    - ip: 192.168.49.1 # minikube ssh 'grep host.minikube.internal /etc/hosts | cut -f1'
    ports:
    - port: 3306
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: bitmaker-celery-beat-service
  labels:
    app: bitmaker-celery-beat
spec:
  ports:
  - port: 8000
    name: bitmaker-celery-beat-port
    protocol: TCP
  selector:
    app: bitmaker-celery-beat
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: bitmaker-celery-worker-service
  labels:
    app: bitmaker-celery-worker
spec:
  ports:
  - port: 8000
    name: bitmaker-celery-worker-port
    protocol: TCP
  selector:
    app: bitmaker-celery-worker
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: bitmaker-redis-service
  labels:
    app: bitmaker-redis
spec:
  ports:
  - port: 6379
    name:  bitmaker-redis-port
    protocol: TCP
  selector:
    app:  bitmaker-redis
