/* tslint:disable */
/* eslint-disable */
/**
 * Bitmaker API v1.0 Documentation
 * Bitmaker API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetRelatedSpidersProject
 */
export interface SetRelatedSpidersProject {
    /**
     * 
     * @type {string}
     * @memberof SetRelatedSpidersProject
     */
    readonly pid?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SetRelatedSpidersProject
     */
    spidersNames: Array<string>;
}

export function SetRelatedSpidersProjectFromJSON(json: any): SetRelatedSpidersProject {
    return SetRelatedSpidersProjectFromJSONTyped(json, false);
}

export function SetRelatedSpidersProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRelatedSpidersProject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pid': !exists(json, 'pid') ? undefined : json['pid'],
        'spidersNames': json['spiders_names'],
    };
}

export function SetRelatedSpidersProjectToJSON(value?: SetRelatedSpidersProject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spiders_names': value.spidersNames,
    };
}


