/* tslint:disable */
/* eslint-disable */
/**
 * Bitmaker API v1.0 Documentation
 * Bitmaker API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpiderJobArg,
    SpiderJobArgFromJSON,
    SpiderJobArgFromJSONTyped,
    SpiderJobArgToJSON,
    SpiderJobEnvVar,
    SpiderJobEnvVarFromJSON,
    SpiderJobEnvVarFromJSONTyped,
    SpiderJobEnvVarToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpiderCronJobCreate
 */
export interface SpiderCronJobCreate {
    /**
     * 
     * @type {number}
     * @memberof SpiderCronJobCreate
     */
    readonly cjid?: number;
    /**
     * 
     * @type {Array<SpiderJobArg>}
     * @memberof SpiderCronJobCreate
     */
    cargs?: Array<SpiderJobArg>;
    /**
     * 
     * @type {Array<SpiderJobEnvVar>}
     * @memberof SpiderCronJobCreate
     */
    cenvVars?: Array<SpiderJobEnvVar>;
    /**
     * 
     * @type {string}
     * @memberof SpiderCronJobCreate
     */
    schedule?: string;
}

export function SpiderCronJobCreateFromJSON(json: any): SpiderCronJobCreate {
    return SpiderCronJobCreateFromJSONTyped(json, false);
}

export function SpiderCronJobCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpiderCronJobCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cjid': !exists(json, 'cjid') ? undefined : json['cjid'],
        'cargs': !exists(json, 'cargs') ? undefined : ((json['cargs'] as Array<any>).map(SpiderJobArgFromJSON)),
        'cenvVars': !exists(json, 'cenv_vars') ? undefined : ((json['cenv_vars'] as Array<any>).map(SpiderJobEnvVarFromJSON)),
        'schedule': !exists(json, 'schedule') ? undefined : json['schedule'],
    };
}

export function SpiderCronJobCreateToJSON(value?: SpiderCronJobCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'cargs': value.cargs === undefined ? undefined : ((value.cargs as Array<any>).map(SpiderJobArgToJSON)),
        'cenv_vars': value.cenvVars === undefined ? undefined : ((value.cenvVars as Array<any>).map(SpiderJobEnvVarToJSON)),
        'schedule': value.schedule,
    };
}


