/* tslint:disable */
/* eslint-disable */
/**
 * Bitmaker API v1.0 Documentation
 * Bitmaker API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpiderJobArg,
    SpiderJobArgFromJSON,
    SpiderJobArgFromJSONTyped,
    SpiderJobArgToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpiderJobCreate
 */
export interface SpiderJobCreate {
    /**
     * 
     * @type {number}
     * @memberof SpiderJobCreate
     */
    readonly jid?: number;
    /**
     * 
     * @type {string}
     * @memberof SpiderJobCreate
     */
    readonly name?: string;
    /**
     * 
     * @type {Array<SpiderJobArg>}
     * @memberof SpiderJobCreate
     */
    args?: Array<SpiderJobArg>;
    /**
     * 
     * @type {string}
     * @memberof SpiderJobCreate
     */
    jobType?: SpiderJobCreateJobTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SpiderJobCreate
     */
    schedule?: string;
    /**
     * 
     * @type {string}
     * @memberof SpiderJobCreate
     */
    readonly jobStatus?: string;
}

/**
* @export
* @enum {string}
*/
export enum SpiderJobCreateJobTypeEnum {
    SingleJob = 'SINGLE_JOB',
    CronJob = 'CRON_JOB'
}

export function SpiderJobCreateFromJSON(json: any): SpiderJobCreate {
    return SpiderJobCreateFromJSONTyped(json, false);
}

export function SpiderJobCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpiderJobCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jid': !exists(json, 'jid') ? undefined : json['jid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'args': !exists(json, 'args') ? undefined : ((json['args'] as Array<any>).map(SpiderJobArgFromJSON)),
        'jobType': !exists(json, 'job_type') ? undefined : json['job_type'],
        'schedule': !exists(json, 'schedule') ? undefined : json['schedule'],
        'jobStatus': !exists(json, 'job_status') ? undefined : json['job_status'],
    };
}

export function SpiderJobCreateToJSON(value?: SpiderJobCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'args': value.args === undefined ? undefined : ((value.args as Array<any>).map(SpiderJobArgToJSON)),
        'job_type': value.jobType,
        'schedule': value.schedule,
    };
}


