version: '3'

services:
  db:
    container_name: bitmaker_db
    image: mysql:8
    volumes:
      - bitmaker_dbdata:/var/lib/mysql
      - ./docker-conf/db/mysql:/docker-entrypoint-initdb.d
    restart: always
    command: --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=YebCEeClTXAJjlQJwv7P
      - MYSQL_USER=django
      - MYSQL_PASSWORD=f074yVBzRRHjuVFtAXJW
    ports:
      - "3306:3306"

  redis:
    container_name: bitmaker_redis
    image: redis:latest
    ports:
      - "6379:6379"

  celery-worker:
    container_name: bitmaker_celery_worker
    build: .
    command: celery -A config.celery worker --loglevel=info
    volumes:
      - .:/home/bitmaker
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - db
      - redis
    restart: on-failure

  celery-beat:
    container_name: bitmaker_celery_beat
    build: .
    command: celery -A config.celery beat --loglevel=info
    volumes:
      - .:/home/bitmaker
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - db
      - redis
      - celery-worker
    restart: on-failure

  web:
    container_name: bitmaker_web
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/bitmaker
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.local
    depends_on:
      - db
      - redis
      - celery-worker
      - celery-beat
    ports:
      - "8000:8000"
    restart: always

volumes:
  bitmaker_dbdata:
