# Generated by Django 3.1.1 on 2021-09-28 18:39

from ***REMOVED***.db import migrations, models
import ***REMOVED***.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_spider_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderJobEnvVar',
            fields=[
                ('evid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('value', models.CharField(max_length=1000)),
                ('job', models.ForeignKey(on_delete=***REMOVED***.db.models.deletion.CASCADE, related_name='env_vars', to='core.spiderjob')),
            ],
        ),
    ]
