# Generated by Django 3.1.1 on 2021-09-14 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_spider_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="spiderjob",
            name="job_type",
        ),
        migrations.RemoveField(
            model_name="spiderjob",
            name="schedule",
        ),
        migrations.CreateModel(
            name="SpiderCronJob",
            fields=[
                ("cjid", models.AutoField(primary_key=True, serialize=False)),
                ("schedule", models.CharField(blank=True, max_length=20)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "spider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cronjobs",
                        to="core.spider",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
