# Generated by Django 3.1.1 on 2021-09-14 22:46

from ***REMOVED***.db import migrations, models
import ***REMOVED***.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_cronjob"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderjob",
            name="cronjob",
            field=models.ForeignKey(
                null=True,
                on_delete=***REMOVED***.db.models.deletion.CASCADE,
                related_name="cronjobs",
                to="core.spidercronjob",
            ),
        ),
        migrations.AddField(
            model_name="spiderjobarg",
            name="cronjob",
            field=models.ForeignKey(
                null=True,
                on_delete=***REMOVED***.db.models.deletion.CASCADE,
                related_name="cjargs",
                to="core.spidercronjob",
            ),
        ),
        migrations.AlterField(
            model_name="spiderjobarg",
            name="job",
            field=models.ForeignKey(
                null=True,
                on_delete=***REMOVED***.db.models.deletion.CASCADE,
                related_name="args",
                to="core.spiderjob",
            ),
        ),
        migrations.AddField(
            model_name="spidercronjob",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
    ]
