/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDetail,
    UserDetailFromJSON,
    UserDetailFromJSONTyped,
    UserDetailToJSON,
} from './';

/**
 * Project Activities.
 * @export
 * @interface Activity
 */
export interface Activity {
    /**
     * 
     * @type {UserDetail}
     * @memberof Activity
     */
    user: UserDetail;
    /**
     * Activity description.
     * @type {string}
     * @memberof Activity
     */
    description: string;
    /**
     * Activity creation date.
     * @type {Date}
     * @memberof Activity
     */
    readonly created?: Date;
}

export function ActivityFromJSON(json: any): Activity {
    return ActivityFromJSONTyped(json, false);
}

export function ActivityFromJSONTyped(json: any, ignoreDiscriminator: boolean): Activity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': UserDetailFromJSON(json['user']),
        'description': json['description'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
    };
}

export function ActivityToJSON(value?: Activity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserDetailToJSON(value.user),
        'description': value.description,
    };
}


