/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKey
 */
export interface ApiKey {
    /**
     * 
     * @type {number}
     * @memberof ApiKey
     */
    readonly id?: number;
    /**
     * What this key is used for.
     * @type {string}
     * @memberof ApiKey
     */
    name: string;
    /**
     * Leading fragment, shown so keys can be told apart.
     * @type {string}
     * @memberof ApiKey
     */
    prefix: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ApiKey
     */
    readonly scopes?: Array<string>;
    /**
     * Creation date.
     * @type {Date}
     * @memberof ApiKey
     */
    readonly created?: Date;
    /**
     * Last time this key authenticated a request.
     * @type {Date}
     * @memberof ApiKey
     */
    lastUsedAt?: Date | null;
}

export function ApiKeyFromJSON(json: any): ApiKey {
    return ApiKeyFromJSONTyped(json, false);
}

export function ApiKeyFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKey {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'prefix': json['prefix'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'lastUsedAt': !exists(json, 'last_used_at') ? undefined : (json['last_used_at'] === null ? null : new Date(json['last_used_at'])),
    };
}

export function ApiKeyToJSON(value?: ApiKey | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'prefix': value.prefix,
        'last_used_at': value.lastUsedAt === undefined ? undefined : (value.lastUsedAt === null ? null : value.lastUsedAt.toISOString()),
    };
}


