/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiKeyCreate
 */
export interface ApiKeyCreate {
    /**
     * What this key is used for.
     * @type {string}
     * @memberof ApiKeyCreate
     */
    name: string;
    /**
     * Extra permissions. Empty means read-only.
     * @type {Array<string>}
     * @memberof ApiKeyCreate
     */
    scopes?: Array<ApiKeyCreateScopesEnum>;
}

/**
* @export
* @enum {string}
*/
export enum ApiKeyCreateScopesEnum {
    Data = 'data',
    Run = 'run',
    Deploy = 'deploy'
}

export function ApiKeyCreateFromJSON(json: any): ApiKeyCreate {
    return ApiKeyCreateFromJSONTyped(json, false);
}

export function ApiKeyCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiKeyCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'scopes': !exists(json, 'scopes') ? undefined : json['scopes'],
    };
}

export function ApiKeyCreateToJSON(value?: ApiKeyCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'scopes': value.scopes,
    };
}


