/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChangePasswordConfirm
 */
export interface ChangePasswordConfirm {
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordConfirm
     */
    oldPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordConfirm
     */
    newPassword: string;
    /**
     * 
     * @type {string}
     * @memberof ChangePasswordConfirm
     */
    newPasswordConfirm: string;
}

export function ChangePasswordConfirmFromJSON(json: any): ChangePasswordConfirm {
    return ChangePasswordConfirmFromJSONTyped(json, false);
}

export function ChangePasswordConfirmFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChangePasswordConfirm {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'oldPassword': json['old_password'],
        'newPassword': json['new_password'],
        'newPasswordConfirm': json['new_password_confirm'],
    };
}

export function ChangePasswordConfirmToJSON(value?: ChangePasswordConfirm | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'old_password': value.oldPassword,
        'new_password': value.newPassword,
        'new_password_confirm': value.newPasswordConfirm,
    };
}


