/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConnectionTest
 */
export interface ConnectionTest {
    /**
     * Whether the connection test was successful.
     * @type {boolean}
     * @memberof ConnectionTest
     */
    success: boolean;
    /**
     * Test result message.
     * @type {string}
     * @memberof ConnectionTest
     */
    message: string;
    /**
     * Additional test details.
     * @type {object}
     * @memberof ConnectionTest
     */
    details?: object;
}

export function ConnectionTestFromJSON(json: any): ConnectionTest {
    return ConnectionTestFromJSONTyped(json, false);
}

export function ConnectionTestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConnectionTest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
        'message': json['message'],
        'details': !exists(json, 'details') ? undefined : json['details'],
    };
}

export function ConnectionTestToJSON(value?: ConnectionTest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
        'message': value.message,
        'details': value.details,
    };
}


