/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataExportList
 */
export interface DataExportList {
    /**
     * Export ID.
     * @type {number}
     * @memberof DataExportList
     */
    readonly eid?: number;
    /**
     * Export status.
     * @type {string}
     * @memberof DataExportList
     */
    readonly status?: string;
    /**
     * 
     * @type {string}
     * @memberof DataExportList
     */
    readonly connectionName?: string;
    /**
     * 
     * @type {string}
     * @memberof DataExportList
     */
    readonly connectionType?: string;
    /**
     * Creation date.
     * @type {Date}
     * @memberof DataExportList
     */
    readonly created?: Date;
    /**
     * Completion time.
     * @type {Date}
     * @memberof DataExportList
     */
    readonly completedAt?: Date;
}

export function DataExportListFromJSON(json: any): DataExportList {
    return DataExportListFromJSONTyped(json, false);
}

export function DataExportListFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExportList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eid': !exists(json, 'eid') ? undefined : json['eid'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'connectionName': !exists(json, 'connection_name') ? undefined : json['connection_name'],
        'connectionType': !exists(json, 'connection_type') ? undefined : json['connection_type'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'completedAt': !exists(json, 'completed_at') ? undefined : (new Date(json['completed_at'])),
    };
}

export function DataExportListToJSON(value?: DataExportList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


