/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataExport
 */
export interface DataExport {
    /**
     * Export ID.
     * @type {number}
     * @memberof DataExport
     */
    readonly eid?: number;
    /**
     * Export status.
     * @type {string}
     * @memberof DataExport
     */
    readonly status?: string;
    /**
     * Airflow DAG run ID.
     * @type {string}
     * @memberof DataExport
     */
    readonly dagRunId?: string;
    /**
     * Airflow DAG name.
     * @type {string}
     * @memberof DataExport
     */
    readonly dagName?: string;
    /**
     * Webhook token.
     * @type {string}
     * @memberof DataExport
     */
    readonly webhookToken?: string;
    /**
     * Export path.
     * @type {string}
     * @memberof DataExport
     */
    readonly exportPath?: string;
    /**
     * Error message.
     * @type {string}
     * @memberof DataExport
     */
    readonly errorMessage?: string;
    /**
     * Start time.
     * @type {Date}
     * @memberof DataExport
     */
    readonly startedAt?: Date;
    /**
     * Completion time.
     * @type {Date}
     * @memberof DataExport
     */
    readonly completedAt?: Date;
    /**
     * Creation date.
     * @type {Date}
     * @memberof DataExport
     */
    readonly created?: Date;
    /**
     * Last update date.
     * @type {Date}
     * @memberof DataExport
     */
    readonly updated?: Date;
    /**
     * 
     * @type {string}
     * @memberof DataExport
     */
    readonly connectionName?: string;
    /**
     * 
     * @type {string}
     * @memberof DataExport
     */
    readonly connectionType?: string;
    /**
     * 
     * @type {number}
     * @memberof DataExport
     */
    readonly spiderJobId?: number;
}

export function DataExportFromJSON(json: any): DataExport {
    return DataExportFromJSONTyped(json, false);
}

export function DataExportFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'eid': !exists(json, 'eid') ? undefined : json['eid'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'dagRunId': !exists(json, 'dag_run_id') ? undefined : json['dag_run_id'],
        'dagName': !exists(json, 'dag_name') ? undefined : json['dag_name'],
        'webhookToken': !exists(json, 'webhook_token') ? undefined : json['webhook_token'],
        'exportPath': !exists(json, 'export_path') ? undefined : json['export_path'],
        'errorMessage': !exists(json, 'error_message') ? undefined : json['error_message'],
        'startedAt': !exists(json, 'started_at') ? undefined : (new Date(json['started_at'])),
        'completedAt': !exists(json, 'completed_at') ? undefined : (new Date(json['completed_at'])),
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'updated': !exists(json, 'updated') ? undefined : (new Date(json['updated'])),
        'connectionName': !exists(json, 'connection_name') ? undefined : json['connection_name'],
        'connectionType': !exists(json, 'connection_type') ? undefined : json['connection_type'],
        'spiderJobId': !exists(json, 'spider_job_id') ? undefined : json['spider_job_id'],
    };
}

export function DataExportToJSON(value?: DataExport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}


