/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataExportCreate
 */
export interface DataExportCreate {
    /**
     * Connection ID to export data to.
     * @type {number}
     * @memberof DataExportCreate
     */
    connection: number;
}

export function DataExportCreateFromJSON(json: any): DataExportCreate {
    return DataExportCreateFromJSONTyped(json, false);
}

export function DataExportCreateFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataExportCreate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'connection': json['connection'],
    };
}

export function DataExportCreateToJSON(value?: DataExportCreate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'connection': value.connection,
    };
}


