/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldCoverageStats
 */
export interface FieldCoverageStats {
    /**
     * 
     * @type {string}
     * @memberof FieldCoverageStats
     */
    fieldName?: string;
    /**
     * 
     * @type {number}
     * @memberof FieldCoverageStats
     */
    fieldCount?: number;
    /**
     * 
     * @type {number}
     * @memberof FieldCoverageStats
     */
    fieldCoverage?: number;
}

export function FieldCoverageStatsFromJSON(json: any): FieldCoverageStats {
    return FieldCoverageStatsFromJSONTyped(json, false);
}

export function FieldCoverageStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldCoverageStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'fieldName': !exists(json, 'field_name') ? undefined : json['field_name'],
        'fieldCount': !exists(json, 'field_count') ? undefined : json['field_count'],
        'fieldCoverage': !exists(json, 'field_coverage') ? undefined : json['field_coverage'],
    };
}

export function FieldCoverageStatsToJSON(value?: FieldCoverageStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'field_name': value.fieldName,
        'field_count': value.fieldCount,
        'field_coverage': value.fieldCoverage,
    };
}


