/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Stats,
    StatsFromJSON,
    StatsFromJSONTyped,
    StatsToJSON,
} from './';

/**
 * 
 * @export
 * @interface GetJobsStats
 */
export interface GetJobsStats {
    /**
     * 
     * @type {number}
     * @memberof GetJobsStats
     */
    jid?: number;
    /**
     * 
     * @type {number}
     * @memberof GetJobsStats
     */
    spider?: number;
    /**
     * 
     * @type {Stats}
     * @memberof GetJobsStats
     */
    stats?: Stats;
}

export function GetJobsStatsFromJSON(json: any): GetJobsStats {
    return GetJobsStatsFromJSONTyped(json, false);
}

export function GetJobsStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJobsStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jid': !exists(json, 'jid') ? undefined : json['jid'],
        'spider': !exists(json, 'spider') ? undefined : json['spider'],
        'stats': !exists(json, 'stats') ? undefined : StatsFromJSON(json['stats']),
    };
}

export function GetJobsStatsToJSON(value?: GetJobsStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jid': value.jid,
        'spider': value.spider,
        'stats': StatsToJSON(value.stats),
    };
}


