/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    JobsMetadata,
    JobsMetadataFromJSON,
    JobsMetadataFromJSONTyped,
    JobsMetadataToJSON,
    Stats,
    StatsFromJSON,
    StatsFromJSONTyped,
    StatsToJSON,
} from './';

/**
 * 
 * @export
 * @interface GlobalStats
 */
export interface GlobalStats {
    /**
     * 
     * @type {Date}
     * @memberof GlobalStats
     */
    date: Date;
    /**
     * 
     * @type {Stats}
     * @memberof GlobalStats
     */
    stats: Stats;
    /**
     * 
     * @type {Array<JobsMetadata>}
     * @memberof GlobalStats
     */
    jobsMetadata: Array<JobsMetadata>;
}

export function GlobalStatsFromJSON(json: any): GlobalStats {
    return GlobalStatsFromJSONTyped(json, false);
}

export function GlobalStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): GlobalStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'date': (new Date(json['date'])),
        'stats': StatsFromJSON(json['stats']),
        'jobsMetadata': ((json['jobs_metadata'] as Array<any>).map(JobsMetadataFromJSON)),
    };
}

export function GlobalStatsToJSON(value?: GlobalStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'date': (value.date.toISOString().substr(0,10)),
        'stats': StatsToJSON(value.stats),
        'jobs_metadata': ((value.jobsMetadata as Array<any>).map(JobsMetadataToJSON)),
    };
}


