/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineResponse2004
 */
export interface InlineResponse2004 {
    /**
     * Memory currently in use (Mi).
     * @type {number}
     * @memberof InlineResponse2004
     */
    memoryUsed?: number;
    /**
     * Owner's total memory quota across all their projects (Mi).
     * @type {number}
     * @memberof InlineResponse2004
     */
    memoryQuota?: number;
    /**
     * Percentage of quota in use.
     * @type {number}
     * @memberof InlineResponse2004
     */
    usedPct?: number;
}

export function InlineResponse2004FromJSON(json: any): InlineResponse2004 {
    return InlineResponse2004FromJSONTyped(json, false);
}

export function InlineResponse2004FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineResponse2004 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'memoryUsed': !exists(json, 'memory_used') ? undefined : json['memory_used'],
        'memoryQuota': !exists(json, 'memory_quota') ? undefined : json['memory_quota'],
        'usedPct': !exists(json, 'used_pct') ? undefined : json['used_pct'],
    };
}

export function InlineResponse2004ToJSON(value?: InlineResponse2004 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'memory_used': value.memoryUsed,
        'memory_quota': value.memoryQuota,
        'used_pct': value.usedPct,
    };
}


