/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
<<<<<<< HEAD
    SpiderJobStats,
    SpiderJobStatsFromJSON,
    SpiderJobStatsFromJSONTyped,
    SpiderJobStatsToJSON,
=======
    SpiderJob,
    SpiderJobFromJSON,
    SpiderJobFromJSONTyped,
    SpiderJobToJSON,
>>>>>>> a0855c1 (Fixed issues with api generation, changed some schema responses and updated viewsets names)
} from './';

/**
 * 
 * @export
 * @interface JobsPagination
 */
export interface JobsPagination {
    /**
     * 
     * @type {number}
     * @memberof JobsPagination
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof JobsPagination
     */
    readonly next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof JobsPagination
     */
    readonly previous?: string | null;
    /**
     * 
<<<<<<< HEAD
     * @type {Array<SpiderJobStats>}
     * @memberof JobsPagination
     */
    results: Array<SpiderJobStats>;
=======
     * @type {Array<SpiderJob>}
     * @memberof JobsPagination
     */
    results: Array<SpiderJob>;
>>>>>>> a0855c1 (Fixed issues with api generation, changed some schema responses and updated viewsets names)
}

export function JobsPaginationFromJSON(json: any): JobsPagination {
    return JobsPaginationFromJSONTyped(json, false);
}

export function JobsPaginationFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsPagination {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
<<<<<<< HEAD
        'results': ((json['results'] as Array<any>).map(SpiderJobStatsFromJSON)),
=======
        'results': ((json['results'] as Array<any>).map(SpiderJobFromJSON)),
>>>>>>> a0855c1 (Fixed issues with api generation, changed some schema responses and updated viewsets names)
    };
}

export function JobsPaginationToJSON(value?: JobsPagination | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
<<<<<<< HEAD
        'results': ((value.results as Array<any>).map(SpiderJobStatsToJSON)),
=======
        'results': ((value.results as Array<any>).map(SpiderJobToJSON)),
>>>>>>> a0855c1 (Fixed issues with api generation, changed some schema responses and updated viewsets names)
    };
}


