/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobStats
 */
export interface JobStats {
    /**
     * 
     * @type {number}
     * @memberof JobStats
     */
    totalJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof JobStats
     */
    runningJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof JobStats
     */
    errorJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof JobStats
     */
    finishedJobs?: number;
}

export function JobStatsFromJSON(json: any): JobStats {
    return JobStatsFromJSONTyped(json, false);
}

export function JobStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalJobs': !exists(json, 'total_jobs') ? undefined : json['total_jobs'],
        'runningJobs': !exists(json, 'running_jobs') ? undefined : json['running_jobs'],
        'errorJobs': !exists(json, 'error_jobs') ? undefined : json['error_jobs'],
        'finishedJobs': !exists(json, 'finished_jobs') ? undefined : json['finished_jobs'],
    };
}

export function JobStatsToJSON(value?: JobStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_jobs': value.totalJobs,
        'running_jobs': value.runningJobs,
        'error_jobs': value.errorJobs,
        'finished_jobs': value.finishedJobs,
    };
}


