/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JobsStats
 */
export interface JobsStats {
    /**
     * 
     * @type {number}
     * @memberof JobsStats
     */
    totalJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof JobsStats
     */
    runningJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof JobsStats
     */
    errorJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof JobsStats
     */
    unknownJobs?: number;
    /**
     * 
     * @type {number}
     * @memberof JobsStats
     */
    finishedJobs?: number;
}

export function JobsStatsFromJSON(json: any): JobsStats {
    return JobsStatsFromJSONTyped(json, false);
}

export function JobsStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobsStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalJobs': !exists(json, 'total_jobs') ? undefined : json['total_jobs'],
        'runningJobs': !exists(json, 'running_jobs') ? undefined : json['running_jobs'],
        'errorJobs': !exists(json, 'error_jobs') ? undefined : json['error_jobs'],
        'unknownJobs': !exists(json, 'unknown_jobs') ? undefined : json['unknown_jobs'],
        'finishedJobs': !exists(json, 'finished_jobs') ? undefined : json['finished_jobs'],
    };
}

export function JobsStatsToJSON(value?: JobsStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_jobs': value.totalJobs,
        'running_jobs': value.runningJobs,
        'error_jobs': value.errorJobs,
        'unknown_jobs': value.unknownJobs,
        'finished_jobs': value.finishedJobs,
    };
}


