/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LogsStats
 */
export interface LogsStats {
    /**
     * 
     * @type {number}
     * @memberof LogsStats
     */
    totalLogs?: number;
    /**
     * 
     * @type {number}
     * @memberof LogsStats
     */
    debugLogs?: number;
    /**
     * 
     * @type {number}
     * @memberof LogsStats
     */
    infoLogs?: number;
    /**
     * 
     * @type {number}
     * @memberof LogsStats
     */
    warningLogs?: number;
    /**
     * 
     * @type {number}
     * @memberof LogsStats
     */
    errorLogs?: number;
    /**
     * 
     * @type {number}
     * @memberof LogsStats
     */
    criticalLogs?: number;
}

export function LogsStatsFromJSON(json: any): LogsStats {
    return LogsStatsFromJSONTyped(json, false);
}

export function LogsStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogsStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'totalLogs': !exists(json, 'total_logs') ? undefined : json['total_logs'],
        'debugLogs': !exists(json, 'debug_logs') ? undefined : json['debug_logs'],
        'infoLogs': !exists(json, 'info_logs') ? undefined : json['info_logs'],
        'warningLogs': !exists(json, 'warning_logs') ? undefined : json['warning_logs'],
        'errorLogs': !exists(json, 'error_logs') ? undefined : json['error_logs'],
        'criticalLogs': !exists(json, 'critical_logs') ? undefined : json['critical_logs'],
    };
}

export function LogsStatsToJSON(value?: LogsStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'total_logs': value.totalLogs,
        'debug_logs': value.debugLogs,
        'info_logs': value.infoLogs,
        'warning_logs': value.warningLogs,
        'error_logs': value.errorLogs,
        'critical_logs': value.criticalLogs,
    };
}


