/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeteringReportResponse
 */
export interface MeteringReportResponse {
    /**
     * 
     * @type {string}
     * @memberof MeteringReportResponse
     */
    id: string;
    /**
     * 
     * @type {Date}
     * @memberof MeteringReportResponse
     */
    recordedAt: Date;
    /**
     * 
     * @type {boolean}
     * @memberof MeteringReportResponse
     */
    duplicate: boolean;
    /**
     * 
     * @type {string}
     * @memberof MeteringReportResponse
     */
    resourceKind: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringReportResponse
     */
    resourceId: string;
}

export function MeteringReportResponseFromJSON(json: any): MeteringReportResponse {
    return MeteringReportResponseFromJSONTyped(json, false);
}

export function MeteringReportResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeteringReportResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'recordedAt': (new Date(json['recorded_at'])),
        'duplicate': json['duplicate'],
        'resourceKind': json['resource_kind'],
        'resourceId': json['resource_id'],
    };
}

export function MeteringReportResponseToJSON(value?: MeteringReportResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'recorded_at': (value.recordedAt.toISOString()),
        'duplicate': value.duplicate,
        'resource_kind': value.resourceKind,
        'resource_id': value.resourceId,
    };
}


