/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MeteringReport
 */
export interface MeteringReport {
    /**
     * Project UUID (``Project.pid``) this usage rolls up to.
     * @type {string}
     * @memberof MeteringReport
     */
    projectId: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringReport
     */
    resourceKind: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringReport
     */
    resourceId: string;
    /**
     * 
     * @type {Date}
     * @memberof MeteringReport
     */
    intervalStart: Date;
    /**
     * 
     * @type {Date}
     * @memberof MeteringReport
     */
    intervalEnd: Date;
    /**
     * Open metric payload (network_bytes, storage_bytes, …).
     * @type {{ [key: string]: object; }}
     * @memberof MeteringReport
     */
    metrics: { [key: string]: object; };
    /**
     * 
     * @type {string}
     * @memberof MeteringReport
     */
    idempotencyKey: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringReport
     */
    kind?: MeteringReportKindEnum;
    /**
     * 
     * @type {string}
     * @memberof MeteringReport
     */
    sourceRef?: string;
    /**
     * Emitting service (e.g. bitmaker-proxy). Defaults to estela.
     * @type {string}
     * @memberof MeteringReport
     */
    reporter?: string;
    /**
     * 
     * @type {string}
     * @memberof MeteringReport
     */
    adjustmentReason?: MeteringReportAdjustmentReasonEnum;
}

/**
* @export
* @enum {string}
*/
export enum MeteringReportKindEnum {
    JobClose = 'JOB_CLOSE',
    DataDelete = 'DATA_DELETE',
    Adjustment = 'ADJUSTMENT',
    DeltaSlice = 'DELTA_SLICE'
}/**
* @export
* @enum {string}
*/
export enum MeteringReportAdjustmentReasonEnum {
    ReconcileScrapyFinal = 'RECONCILE_SCRAPY_FINAL',
    ReconcileStorage = 'RECONCILE_STORAGE',
    Manual = 'MANUAL'
}

export function MeteringReportFromJSON(json: any): MeteringReport {
    return MeteringReportFromJSONTyped(json, false);
}

export function MeteringReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): MeteringReport {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'projectId': json['project_id'],
        'resourceKind': json['resource_kind'],
        'resourceId': json['resource_id'],
        'intervalStart': (new Date(json['interval_start'])),
        'intervalEnd': (new Date(json['interval_end'])),
        'metrics': json['metrics'],
        'idempotencyKey': json['idempotency_key'],
        'kind': !exists(json, 'kind') ? undefined : json['kind'],
        'sourceRef': !exists(json, 'source_ref') ? undefined : json['source_ref'],
        'reporter': !exists(json, 'reporter') ? undefined : json['reporter'],
        'adjustmentReason': !exists(json, 'adjustment_reason') ? undefined : json['adjustment_reason'],
    };
}

export function MeteringReportToJSON(value?: MeteringReport | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'project_id': value.projectId,
        'resource_kind': value.resourceKind,
        'resource_id': value.resourceId,
        'interval_start': (value.intervalStart.toISOString()),
        'interval_end': (value.intervalEnd.toISOString()),
        'metrics': value.metrics,
        'idempotency_key': value.idempotencyKey,
        'kind': value.kind,
        'source_ref': value.sourceRef,
        'reporter': value.reporter,
        'adjustment_reason': value.adjustmentReason,
    };
}


