/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDetail,
    UserDetailFromJSON,
    UserDetailFromJSONTyped,
    UserDetailToJSON,
} from './';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * A unique integer value identifying each notification
     * @type {number}
     * @memberof Notification
     */
    readonly nid?: number;
    /**
     * 
     * @type {UserDetail}
     * @memberof Notification
     */
    user: UserDetail;
    /**
     * Notifications message.
     * @type {string}
     * @memberof Notification
     */
    message: string;
    /**
     * Project to which the notifications corresponds.
     * @type {string}
     * @memberof Notification
     */
    project: string;
    /**
     * Whether the notification was seen.
     * @type {boolean}
     * @memberof Notification
     */
    seen?: boolean;
    /**
     * Notification send date.
     * @type {Date}
     * @memberof Notification
     */
    readonly createdAt?: Date;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nid': !exists(json, 'nid') ? undefined : json['nid'],
        'user': UserDetailFromJSON(json['user']),
        'message': json['message'],
        'project': json['project'],
        'seen': !exists(json, 'seen') ? undefined : json['seen'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function NotificationToJSON(value?: Notification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserDetailToJSON(value.user),
        'message': value.message,
        'project': value.project,
        'seen': value.seen,
    };
}


