/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Activity,
    ActivityFromJSON,
    ActivityFromJSONTyped,
    ActivityToJSON,
} from './';

/**
 * 
 * @export
 * @interface Notification
 */
export interface Notification {
    /**
     * A unique integer value identifying each notification
     * @type {number}
     * @memberof Notification
     */
    readonly nid?: number;
    /**
     * 
     * @type {Activity}
     * @memberof Notification
     */
    activity: Activity;
    /**
     * Whether the notification was seen.
     * @type {boolean}
     * @memberof Notification
     */
    seen?: boolean;
}

export function NotificationFromJSON(json: any): Notification {
    return NotificationFromJSONTyped(json, false);
}

export function NotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Notification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nid': !exists(json, 'nid') ? undefined : json['nid'],
        'activity': ActivityFromJSON(json['activity']),
        'seen': !exists(json, 'seen') ? undefined : json['seen'],
    };
}

export function NotificationToJSON(value?: Notification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'activity': ActivityToJSON(value.activity),
        'seen': value.seen,
    };
}


