/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UserDetail,
    UserDetailFromJSON,
    UserDetailFromJSONTyped,
    UserDetailToJSON,
} from './';

/**
 * Users with permissions on this project.
 * @export
 * @interface Permission
 */
export interface Permission {
    /**
     * 
     * @type {UserDetail}
     * @memberof Permission
     */
    user?: UserDetail;
    /**
     * Permission on this project.
     * @type {string}
     * @memberof Permission
     */
    permission?: PermissionPermissionEnum;
}

/**
* @export
* @enum {string}
*/
export enum PermissionPermissionEnum {
    Admin = 'ADMIN',
    Developer = 'DEVELOPER',
    Viewer = 'VIEWER'
}

export function PermissionFromJSON(json: any): Permission {
    return PermissionFromJSONTyped(json, false);
}

export function PermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): Permission {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'user': !exists(json, 'user') ? undefined : UserDetailFromJSON(json['user']),
        'permission': !exists(json, 'permission') ? undefined : json['permission'],
    };
}

export function PermissionToJSON(value?: Permission | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user': UserDetailToJSON(value.user),
        'permission': value.permission,
    };
}


