/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ProjectUsage
 */
export interface ProjectUsage {
    /**
     * 
     * @type {string}
     * @memberof ProjectUsage
     */
    readonly pid?: string;
    /**
     * 
     * @type {string}
     * @memberof ProjectUsage
     */
    readonly name?: string;
    /**
     * Amount of network bytes used.
     * @type {number}
     * @memberof ProjectUsage
     */
    networkUsage: number;
    /**
     * 
     * @type {string}
     * @memberof ProjectUsage
     */
    readonly processingTime?: string;
    /**
     * Amount of items extracted.
     * @type {number}
     * @memberof ProjectUsage
     */
    itemCount: number;
    /**
     * Amount of requests made.
     * @type {number}
     * @memberof ProjectUsage
     */
    requestCount: number;
    /**
     * Amount in bytes occupied by items in the database
     * @type {number}
     * @memberof ProjectUsage
     */
    itemsDataSize: number;
    /**
     * Amount in bytes occupied by requests in the database
     * @type {number}
     * @memberof ProjectUsage
     */
    requestsDataSize: number;
    /**
     * Amount in bytes occupied by logs in the database
     * @type {number}
     * @memberof ProjectUsage
     */
    logsDataSize: number;
}

export function ProjectUsageFromJSON(json: any): ProjectUsage {
    return ProjectUsageFromJSONTyped(json, false);
}

export function ProjectUsageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectUsage {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'pid': !exists(json, 'pid') ? undefined : json['pid'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'networkUsage': json['network_usage'],
        'processingTime': !exists(json, 'processing_time') ? undefined : json['processing_time'],
        'itemCount': json['item_count'],
        'requestCount': json['request_count'],
        'itemsDataSize': json['items_data_size'],
        'requestsDataSize': json['requests_data_size'],
        'logsDataSize': json['logs_data_size'],
    };
}

export function ProjectUsageToJSON(value?: ProjectUsage | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'network_usage': value.networkUsage,
        'item_count': value.itemCount,
        'request_count': value.requestCount,
        'items_data_size': value.itemsDataSize,
        'requests_data_size': value.requestsDataSize,
        'logs_data_size': value.logsDataSize,
    };
}


