/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SpiderJobArg,
    SpiderJobArgFromJSON,
    SpiderJobArgFromJSONTyped,
    SpiderJobArgToJSON,
    SpiderJobEnvVar,
    SpiderJobEnvVarFromJSON,
    SpiderJobEnvVarFromJSONTyped,
    SpiderJobEnvVarToJSON,
    SpiderJobTag,
    SpiderJobTagFromJSON,
    SpiderJobTagFromJSONTyped,
    SpiderJobTagToJSON,
} from './';

/**
 * 
 * @export
 * @interface SpiderCronJob
 */
export interface SpiderCronJob {
    /**
     * 
     * @type {number}
     * @memberof SpiderCronJob
     */
    readonly cjid?: number;
    /**
     * 
     * @type {number}
     * @memberof SpiderCronJob
     */
    spider: number;
    /**
     * 
     * @type {Date}
     * @memberof SpiderCronJob
     */
    readonly created?: Date;
    /**
     * 
     * @type {string}
     * @memberof SpiderCronJob
     */
    readonly name?: string;
    /**
     * 
     * @type {Array<SpiderJobArg>}
     * @memberof SpiderCronJob
     */
    cargs?: Array<SpiderJobArg>;
    /**
     * 
     * @type {Array<SpiderJobEnvVar>}
     * @memberof SpiderCronJob
     */
    cenvVars?: Array<SpiderJobEnvVar>;
    /**
     * 
     * @type {Array<SpiderJobTag>}
     * @memberof SpiderCronJob
     */
    ctags?: Array<SpiderJobTag>;
    /**
     * 
     * @type {string}
     * @memberof SpiderCronJob
     */
    schedule?: string;
    /**
     * 
     * @type {string}
     * @memberof SpiderCronJob
     */
    status?: SpiderCronJobStatusEnum;
    /**
     * 
     * @type {boolean}
     * @memberof SpiderCronJob
     */
    uniqueCollection?: boolean;
}

/**
* @export
* @enum {string}
*/
export enum SpiderCronJobStatusEnum {
    Active = 'ACTIVE',
    Disabled = 'DISABLED'
}

export function SpiderCronJobFromJSON(json: any): SpiderCronJob {
    return SpiderCronJobFromJSONTyped(json, false);
}

export function SpiderCronJobFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpiderCronJob {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'cjid': !exists(json, 'cjid') ? undefined : json['cjid'],
        'spider': json['spider'],
        'created': !exists(json, 'created') ? undefined : (new Date(json['created'])),
        'name': !exists(json, 'name') ? undefined : json['name'],
        'cargs': !exists(json, 'cargs') ? undefined : ((json['cargs'] as Array<any>).map(SpiderJobArgFromJSON)),
        'cenvVars': !exists(json, 'cenv_vars') ? undefined : ((json['cenv_vars'] as Array<any>).map(SpiderJobEnvVarFromJSON)),
        'ctags': !exists(json, 'ctags') ? undefined : ((json['ctags'] as Array<any>).map(SpiderJobTagFromJSON)),
        'schedule': !exists(json, 'schedule') ? undefined : json['schedule'],
        'status': !exists(json, 'status') ? undefined : json['status'],
        'uniqueCollection': !exists(json, 'unique_collection') ? undefined : json['unique_collection'],
    };
}

export function SpiderCronJobToJSON(value?: SpiderCronJob | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'spider': value.spider,
        'cargs': value.cargs === undefined ? undefined : ((value.cargs as Array<any>).map(SpiderJobArgToJSON)),
        'cenv_vars': value.cenvVars === undefined ? undefined : ((value.cenvVars as Array<any>).map(SpiderJobEnvVarToJSON)),
        'ctags': value.ctags === undefined ? undefined : ((value.ctags as Array<any>).map(SpiderJobTagToJSON)),
        'schedule': value.schedule,
        'status': value.status,
        'unique_collection': value.uniqueCollection,
    };
}


