/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Job arguments.
 * @export
 * @interface SpiderJobArg
 */
export interface SpiderJobArg {
    /**
     * Argument name.
     * @type {string}
     * @memberof SpiderJobArg
     */
    name: string;
    /**
     * Argument value.
     * @type {string}
     * @memberof SpiderJobArg
     */
    value: string;
}

export function SpiderJobArgFromJSON(json: any): SpiderJobArg {
    return SpiderJobArgFromJSONTyped(json, false);
}

export function SpiderJobArgFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpiderJobArg {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'value': json['value'],
    };
}

export function SpiderJobArgToJSON(value?: SpiderJobArg | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}


