/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    CoverageStats,
    CoverageStatsFromJSON,
    CoverageStatsFromJSONTyped,
    CoverageStatsToJSON,
    JobsStats,
    JobsStatsFromJSON,
    JobsStatsFromJSONTyped,
    JobsStatsToJSON,
    LogsStats,
    LogsStatsFromJSON,
    LogsStatsFromJSONTyped,
    LogsStatsToJSON,
    PagesStats,
    PagesStatsFromJSON,
    PagesStatsFromJSONTyped,
    PagesStatsToJSON,
    StatusCodesStats,
    StatusCodesStatsFromJSON,
    StatusCodesStatsFromJSONTyped,
    StatusCodesStatsToJSON,
} from './';

/**
 * 
 * @export
 * @interface Stats
 */
export interface Stats {
    /**
     * 
     * @type {JobsStats}
     * @memberof Stats
     */
    jobs: JobsStats;
    /**
     * 
     * @type {PagesStats}
     * @memberof Stats
     */
    pages: PagesStats;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    itemsCount?: number;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    runtime?: number;
    /**
     * 
     * @type {StatusCodesStats}
     * @memberof Stats
     */
    statusCodes: StatusCodesStats;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    successRate?: number;
    /**
     * 
     * @type {LogsStats}
     * @memberof Stats
     */
    logs: LogsStats;
    /**
     * 
     * @type {CoverageStats}
     * @memberof Stats
     */
    coverage: CoverageStats;
}

export function StatsFromJSON(json: any): Stats {
    return StatsFromJSONTyped(json, false);
}

export function StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'jobs': JobsStatsFromJSON(json['jobs']),
        'pages': PagesStatsFromJSON(json['pages']),
        'itemsCount': !exists(json, 'items_count') ? undefined : json['items_count'],
        'runtime': !exists(json, 'runtime') ? undefined : json['runtime'],
        'statusCodes': StatusCodesStatsFromJSON(json['status_codes']),
        'successRate': !exists(json, 'success_rate') ? undefined : json['success_rate'],
        'logs': LogsStatsFromJSON(json['logs']),
        'coverage': CoverageStatsFromJSON(json['coverage']),
    };
}

export function StatsToJSON(value?: Stats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'jobs': JobsStatsToJSON(value.jobs),
        'pages': PagesStatsToJSON(value.pages),
        'items_count': value.itemsCount,
        'runtime': value.runtime,
        'status_codes': StatusCodesStatsToJSON(value.statusCodes),
        'success_rate': value.successRate,
        'logs': LogsStatsToJSON(value.logs),
        'coverage': CoverageStatsToJSON(value.coverage),
    };
}


