/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StatusCodesStats
 */
export interface StatusCodesStats {
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status200?: number;
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status301?: number;
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status302?: number;
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status401?: number;
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status403?: number;
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status404?: number;
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status429?: number;
    /**
     * 
     * @type {number}
     * @memberof StatusCodesStats
     */
    status500?: number;
}

export function StatusCodesStatsFromJSON(json: any): StatusCodesStats {
    return StatusCodesStatsFromJSONTyped(json, false);
}

export function StatusCodesStatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): StatusCodesStats {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status200': !exists(json, 'status_200') ? undefined : json['status_200'],
        'status301': !exists(json, 'status_301') ? undefined : json['status_301'],
        'status302': !exists(json, 'status_302') ? undefined : json['status_302'],
        'status401': !exists(json, 'status_401') ? undefined : json['status_401'],
        'status403': !exists(json, 'status_403') ? undefined : json['status_403'],
        'status404': !exists(json, 'status_404') ? undefined : json['status_404'],
        'status429': !exists(json, 'status_429') ? undefined : json['status_429'],
        'status500': !exists(json, 'status_500') ? undefined : json['status_500'],
    };
}

export function StatusCodesStatsToJSON(value?: StatusCodesStats | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status_200': value.status200,
        'status_301': value.status301,
        'status_302': value.status302,
        'status_401': value.status401,
        'status_403': value.status403,
        'status_404': value.status404,
        'status_429': value.status429,
        'status_500': value.status500,
    };
}


