/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserProfileUpdate
 */
export interface UserProfileUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserProfileUpdate
     */
    readonly lastPasswordChange?: string;
}

export function UserProfileUpdateFromJSON(json: any): UserProfileUpdate {
    return UserProfileUpdateFromJSONTyped(json, false);
}

export function UserProfileUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserProfileUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'password': json['password'],
        'lastPasswordChange': !exists(json, 'last_password_change') ? undefined : json['last_password_change'],
    };
}

export function UserProfileUpdateToJSON(value?: UserProfileUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'password': value.password,
    };
}


