/* tslint:disable */
/* eslint-disable */
/**
 * estela API v1.0 Documentation
 * estela API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Notification,
    NotificationFromJSON,
    NotificationFromJSONTyped,
    NotificationToJSON,
} from './';

/**
 * 
 * @export
 * @interface UserNotification
 */
export interface UserNotification {
    /**
     * 
     * @type {number}
     * @memberof UserNotification
     */
    readonly id?: number;
    /**
     * 
     * @type {Notification}
     * @memberof UserNotification
     */
    notification?: Notification;
    /**
     * Whether the notification was seen.
     * @type {boolean}
     * @memberof UserNotification
     */
    seen?: boolean;
    /**
     * Subscription date.
     * @type {Date}
     * @memberof UserNotification
     */
    readonly createdAt?: Date;
}

export function UserNotificationFromJSON(json: any): UserNotification {
    return UserNotificationFromJSONTyped(json, false);
}

export function UserNotificationFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserNotification {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'notification': !exists(json, 'notification') ? undefined : NotificationFromJSON(json['notification']),
        'seen': !exists(json, 'seen') ? undefined : json['seen'],
        'createdAt': !exists(json, 'created_at') ? undefined : (new Date(json['created_at'])),
    };
}

export function UserNotificationToJSON(value?: UserNotification | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'notification': NotificationToJSON(value.notification),
        'seen': value.seen,
    };
}


