version: '3'

services:
  db:
    container_name: estela_db
    image: mysql:8
    volumes:
      - estela_dbdata:/var/lib/mysql
      - ./docker-conf/db/mysql:/docker-entrypoint-initdb.d
    restart: always
    command: --default_authentication_plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=YebCEeClTXAJjlQJwv7P
    ports:
      - "3306:3306"
      
  registry:
    container_name: estela_registry
    restart: always
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry_data:/var/lib/registry
  
  minio:
    container_name: estela_storage
    restart: always
    image: minio/minio
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - datastore:/data
    command: server /data --console-address ":9001"

  mongo:
    container_name: estela_mongo
    restart: always
    image: mongo:4.4.14
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
    ports:
      - 27017:27017
    volumes:
      - estela_mongodata:/data
    command: mongod --bind_ip_all

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:mongoadmin@mongo:27017/

volumes:
  estela_dbdata:
  registry_data:
  datastore:
  estela_mongodata:
