kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: estela-django-api
spec:
  selector:
    matchLabels:
      app: estela-django-api
  template:
    metadata:
      labels:
        app: estela-django-api
    spec:
      serviceAccountName: estela-api
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: estela-django-api
        image: {{ .Values.registryHost }}/estela-django-api:latest
        imagePullPolicy: Always
        command: ['gunicorn', 'config.wsgi', '--bind=0.0.0.0:8000']
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-config
      {{- if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: estela-celery-beat
spec:
  selector:
    matchLabels:
      app: estela-celery-beat
  template:
    metadata:
      labels:
        app: estela-celery-beat
    spec:
      serviceAccountName: estela-api
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: estela-celery-beat
        image: {{ .Values.registryHost }}/estela-celery-beat:latest
        command: ['celery', '-A', 'config.celery', 'beat', '--loglevel=info']
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-config
      {{- if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: estela-celery-worker
spec:
  selector:
    matchLabels:
      app: estela-celery-worker
  template:
    metadata:
      labels:
        app: estela-celery-worker
    spec:
      serviceAccountName: estela-api
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: estela-celery-worker
        image: {{ .Values.registryHost }}/estela-celery-worker:latest
        command: ['celery', '-A', 'config.celery', 'worker', '--loglevel=info']
        envFrom:
        - secretRef:
            name: api-secrets
        - configMapRef:
            name: api-config
      {{- if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: estela-redis
spec:
  selector:
    matchLabels:
      app: estela-redis
  template:
    metadata:
      labels:
        app: estela-redis
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: estela-redis
        image: {{ .Values.registryHost }}/estela-redis:latest
      {{- if .Values.nodeSelector }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
