apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.DB_USER | b64enc }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD | b64enc }}
  SPIDERDATA_DB_CONNECTION: {{ .Values.SPIDERDATA_DB_CONNECTION | b64enc }}
  EMAIL_HOST_USER: {{ .Values.EMAIL_HOST_USER | b64enc }}
  EMAIL_HOST_PASSWORD: {{ .Values.EMAIL_HOST_PASSWORD | b64enc }}
  SECRET_KEY: {{ .Values.SECRET_KEY | b64enc }}
  EXTERNAL_APP_KEYS: {{ .Values.EXTERNAL_APP_KEYS | b64enc }}
  {{- if .Values.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID | b64enc }}
  {{- end }}
  {{- if .Values.AWS_SECRET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY | b64enc }}
  {{- end }}
