apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: {{ .Release.Namespace }}
data:
  DB_HOST: {{ .Values.DB_HOST }}
  DB_PORT: {{ .Values.DB_PORT | quote }}
  DB_NAME: {{ .Values.DB_NAME }}
  REGISTRY_HOST: {{ .Values.REGISTRY_HOST }}
  REPOSITORY_NAME: {{ .Values.REPOSITORY_NAME }}
  CORS_ORIGIN_WHITELIST: {{ .Values.CORS_ORIGIN_WHITELIST }}
  {{- range $key, $val := .Values.QUEUE_PARAMETERS }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  DJANGO_SETTINGS_MODULE: {{ .Values.DJANGO_SETTINGS_MODULE }}
  CELERY_BROKER_URL: {{ .Values.CELERY_BROKER_URL }}
  CELERY_RESULT_BACKEND: {{ .Values.CELERY_RESULT_BACKEND }}
  CELERY_EXTERNAL_IMPORTS: {{ .Values.CELERY_EXTERNAL_IMPORTS }}
  BUCKET_NAME_PROJECTS: {{ .Values.BUCKET_NAME_PROJECTS }}
  ENGINE: {{ .Values.ENGINE }}
  CREDENTIALS: {{ .Values.CREDENTIALS }}
  EMAIL_HOST: {{ .Values.EMAIL_HOST }}
  EMAIL_PORT: {{ .Values.EMAIL_PORT | quote }}
  EMAILS_TO_ALERT: {{ .Values.EMAILS_TO_ALERT }}
  VERIFICATION_EMAIL: {{ .Values.VERIFICATION_EMAIL }}
  REGISTER: {{ .Values.REGISTER | quote }}
  DJANGO_API_HOST: http://{{ .Values.DJANGO_API_HOST }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.DJANGO_API_HOST }},127.0.0.1
  STAGE: {{ .Values.STAGE }}
  SPIDERDATA_DB_ENGINE: {{ .Values.SPIDERDATA_DB_ENGINE }}
  SPIDERDATA_DB_CERTIFICATE_PATH: {{ .Values.SPIDERDATA_DB_CERTIFICATE_PATH }}
  {{- if .Values.AWS_DEFAULT_REGION }}
  AWS_DEFAULT_REGION: {{ .Values.AWS_DEFAULT_REGION }}
  {{- end }}
  {{- if .Values.REGISTRY_ID }}
  REGISTRY_ID: {{ .Values.REGISTRY_ID | quote }}
  {{- end }}
  DJANGO_EXTERNAL_APPS: {{ .Values.DJANGO_EXTERNAL_APPS | quote }}
  EXTERNAL_MIDDLEWARES: {{ .Values.EXTERNAL_MIDDLEWARES | quote }}

