apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret }}
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.DB_USER }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD }}
  MONGO_CONNECTION: {{ .Values.MONGO_CONNECTION }}
  EMAIL_HOST_USER: {{ .Values.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: {{ .Values.EMAIL_HOST_PASSWORD }}
  SECRET_KEY: {{ .Values.SECRET_KEY }}
  {{- if .Values.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID }}
  {{- end }}
  {{- if .Values.AWS_SECRET_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY }}
  {{- end }}
