{{- if .Values.awsRegistry }}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ .Release.Namespace }}
  name: estela-registry
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: {{ .Release.Namespace }}
  name: estela-registry-role
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: estela-registry-bind
subjects:
- kind: ServiceAccount
  name: estela-registry
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: estela-registry-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: job-ecr-kube-helper
  labels:
    app: job-ecr-kube-helper
spec:
  ttlSecondsAfterFinished: 60
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: estela-registry
      containers:
      - name: pod-ecr-kube-helper
        image: anaganisk/ecr-kube-helper:1.0.0
        imagePullPolicy: IfNotPresent
        env:
        - name: AWS_DEFAULT_REGION
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: AWS_DEFAULT_REGION
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: api-secrets
              key: AWS_SECRET_ACCESS_KEY
        - name: TARGET_ECR
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: REGISTRY_ID
        - name: LOGLEVEL
          value: INFO
        - name: TARGET_SECRET
          value: regcred
        - name: TARGET_NAMESPACE
          value: {{ .Release.Namespace }}
        - name: TARGET_EMAIL
          value: estela@estela.dev
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: {{ .Release.Namespace }}
  name: cron-ecr-kube-helper
  labels:
    app: cron-ecr-kube-helper
spec:
  schedule: "0 */12 * * *" # Update the token every 12h
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: estela-registry
          containers:
          - name: pod-ecr-kube-helper
            image: anaganisk/ecr-kube-helper:1.0.0
            imagePullPolicy: IfNotPresent
            env:
            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: AWS_DEFAULT_REGION
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: api-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: TARGET_ECR
              valueFrom:
                configMapKeyRef:
                  name: api-config
                  key: REGISTRY_ID
            - name: LOGLEVEL
              value: INFO
            - name: TARGET_SECRET
              value: regcred
            - name: TARGET_NAMESPACE
              value: {{ .Release.Namespace }}
            - name: TARGET_EMAIL
              value: estela@estela.dev
{{- end}}
