/* tslint:disable */
/* eslint-disable */
/**
 * Bitmaker API v1.0 Documentation
 * Bitmaker API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject
 */
export interface InlineObject {
    /**
     * Action to perform
     * @type {string}
     * @memberof InlineObject
     */
    action?: string;
    /**
     * User's email
     * @type {string}
     * @memberof InlineObject
     */
    email?: string;
    /**
     * Project Name
     * @type {string}
     * @memberof InlineObject
     */
    name: string;
    /**
     * Type of permission
     * @type {string}
     * @memberof InlineObject
     */
    permission?: string;
}

export function InlineObjectFromJSON(json: any): InlineObject {
    return InlineObjectFromJSONTyped(json, false);
}

export function InlineObjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'action': !exists(json, 'action') ? undefined : json['action'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'name': json['name'],
        'permission': !exists(json, 'permission') ? undefined : json['permission'],
    };
}

export function InlineObjectToJSON(value?: InlineObject | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'action': value.action,
        'email': value.email,
        'name': value.name,
        'permission': value.permission,
    };
}


