/* tslint:disable */
/* eslint-disable */
/**
 * Bitmaker API v1.0 Documentation
 * Bitmaker API Swagger Specification
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SpiderJobTag
 */
export interface SpiderJobTag {
    /**
     * 
     * @type {string}
     * @memberof SpiderJobTag
     */
    name: string;
}

export function SpiderJobTagFromJSON(json: any): SpiderJobTag {
    return SpiderJobTagFromJSONTyped(json, false);
}

export function SpiderJobTagFromJSONTyped(json: any, ignoreDiscriminator: boolean): SpiderJobTag {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
    };
}

export function SpiderJobTagToJSON(value?: SpiderJobTag | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}


