FROM python:3.6

WORKDIR /home/estela

COPY bitmaker-api/requirements ./requirements

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN pip install -r requirements/test.txt

COPY bitmaker-api/ .
COPY database_adapters/ ./database_adapters
