FROM python:3.9

WORKDIR /home/estela

ARG APPLE_SILICON_LOCAL=false
COPY estela-api/requirements ./requirements

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

RUN apt-get update

RUN apt-get install \
    ca-certificates \
    curl \
    gnupg \
    lsb-release -y

RUN curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg

RUN echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu \
  focal stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

RUN apt-get update

RUN apt-get install docker-ce docker-ce-cli containerd.io -y

# If M1 chip is used, install pyodbc and unixodbc-dev
RUN if [ "$APPLE_SILICON_LOCAL" = "true" ]; then \
        apt-get update && apt-get install -y unixodbc-dev && \
        pip install --no-binary :all: pyodbc && \
        sed -i '/pyodbc/d' requirements/deploy.txt; \
    fi

RUN pip install -r requirements/deploy.txt
RUN if test -f "requirements/externalApps.txt"; then pip install -r requirements/externalApps.txt; fi

COPY estela-api/ estela-api/
COPY database_adapters/ estela-api/database_adapters/
