kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: kafka-items-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_items']
        envFrom:
        - secretRef:
            name: kafka-secrets
        - configMapRef:
            name: kafka-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: kafka-requests-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_requests']
        envFrom:
        - secretRef:
            name: kafka-secrets
        - configMapRef:
            name: kafka-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: kafka-stats-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_stats']
        envFrom:
        - secretRef:
            name: kafka-secrets
        - configMapRef:
            name: kafka-config
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: kafka-logs-consumer
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_logs']
        envFrom:
        - secretRef:
            name: kafka-secrets
        - configMapRef:
            name: kafka-config