kind: Service
apiVersion: v1
metadata:
  namespace: default
  name: kafka
spec:
  ports:
  - name: broker
    protocol: TCP
    port: 9092
    targetPort: 9092
    nodePort: 0
---
{{- if .Values.Local }}
kind: Endpoints
apiVersion: v1
metadata:
  namespace: default
  name: kafka
subsets:
- addresses:
  - ip: 192.168.49.1 # minikube ssh 'grep host.minikube.internal /etc/hosts | cut -f1'
  ports:
  - name: broker
    port: 9092
{{- end  }}
