apiVersion: v1
kind: Secret
metadata:
  name: api-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DB_USER: {{ .Values.DB_USER }}
  DB_PASSWORD: {{ .Values.DB_PASSWORD }}
  AWS_ACCESS_KEY_ID: {{ .Values.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.AWS_SECRET_ACCESS_KEY }}
  MONGO_CONNECTION: {{ .Values.MONGO_CONNECTION }}
  SECRET_KEY: {{ .Values.SECRET_KEY }}
  ELASTICSEARCH_USER: {{ .Values.ELASTICSEARCH_USER }}
  ELASTICSEARCH_PASS: {{ .Values.ELASTICSEARCH_PASS }}
  EMAIL_HOST_USER: {{ .Values.EMAIL_HOST_USER }}
  EMAIL_HOST_PASSWORD: {{ .Values.EMAIL_HOST_PASSWORD }}
