REGISTRY_HOST = 192.168.49.1:5000# minikube ssh 'grep host.minikube.internal /etc/hosts | cut -f1'
REGION = us-east-2
DEVTAG = latest#dev-$$USER

ifeq ($(OS),Windows_NT)
	DOCKER_COMPOSE = docker compose
else
	UNAME_S := $(shell uname -s)
	ifeq ($(UNAME_S),Linux)
		DOCKER_COMPOSE = docker-compose
	else # OSX
		DOCKER_COMPOSE = docker compose
	endif
endif

.PHONY: login-ecr
login-ecr:
	-aws ecr get-login-password --region $(REGION) | docker login \
	   --username AWS --password-stdin  $(REGISTRY_HOST)


.PHONY: start
start:
	-$(DOCKER_COMPOSE) up -d


.PHONY: stop
stop:
	-$(DOCKER_COMPOSE) stop


.PHONY: setup
setup: build-consumer-image upload-consumer-image
	-$(DOCKER_COMPOSE) up -d
	-kubectl apply -f kubernetes/bitmaker-kafka-secrets.yaml
	-kubectl apply -f kubernetes/bitmaker-kafka-services.yaml
	-kubectl apply -f kubernetes/bitmaker-kafka-consumers.yaml
	-kubectl set image deployment/kafka-logs-consumer consumer=$(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)
	-kubectl set image deployment/kafka-items-consumer consumer=$(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)
	-kubectl set image deployment/kafka-requests-consumer consumer=$(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)


.PHONY: down
down:
	-kubectl delete -f kubernetes/bitmaker-kafka-secrets.yaml
	-kubectl delete -f kubernetes/bitmaker-kafka-services.yaml
	-kubectl delete -f kubernetes/bitmaker-kafka-consumers.yaml
	-$(DOCKER_COMPOSE) down


.PHONY: rebuild
rebuild: build-consumer-image upload-consumer-image
	-kubectl apply -f kubernetes/bitmaker-kafka-secrets.yaml
	-kubectl apply -f kubernetes/bitmaker-kafka-consumers.yaml
	-kubectl rollout restart deployment kafka-logs-consumer
	-kubectl set image deployment/kafka-logs-consumer consumer=$(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)
	-kubectl rollout restart deployment kafka-items-consumer
	-kubectl set image deployment/kafka-items-consumer consumer=$(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)
	-kubectl rollout restart deployment kafka-requests-consumer
	-kubectl set image deployment/kafka-requests-consumer consumer=$(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)


.PHONY: build-consumer-image
build-consumer-image:
	-docker build .. --file bitmaker-kafka/Dockerfile --tag bitmaker-consumer:$(DEVTAG)


.PHONY: upload-consumer-image
upload-consumer-image: login-ecr
	-docker tag bitmaker-consumer:$(DEVTAG) $(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)
	-docker push $(REGISTRY_HOST)/bitmaker-consumer:$(DEVTAG)


.PHONY: set-up-image
set-up-images: build-consumer-image upload-consumer-images


.PHONY: lint
lint:
	-black .
