# Generated by Django 3.1.1 on 2021-07-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20210725_2145"),
    ]

    operations = [
        migrations.AddField(
            model_name="spider",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
