# Generated by Django 3.1.1 on 2021-09-30 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_linkcronjob"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spiderjobarg",
            name="cronjob",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cargs",
                to="core.spidercronjob",
            ),
        ),
        migrations.CreateModel(
            name="SpiderJobEnvVar",
            fields=[
                ("evid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=1000)),
                ("value", models.CharField(max_length=1000)),
                (
                    "cronjob",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cenv_vars",
                        to="core.spidercronjob",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="env_vars",
                        to="core.spiderjob",
                    ),
                ),
            ],
        ),
    ]
