# Generated by Django 3.1.1 on 2021-12-14 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_passuserstonewmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="users",
        ),
    ]
