# Generated by Django 3.1.1 on 2022-09-17 22:17

from django.db import migrations


def modify_permission(apps, schema_editor):
    Permission = apps.get_model("core", "Permission")
    for permission in Permission.objects.all():
        if permission.permission == "OWNER":
            permission.permission = "ADMIN"
        if permission.permission == "EDITOR":
            permission.permission = "DEVELOPER"

        permission.save(update_fields=["permission"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_auto_20220917_2149"),
    ]

    operations = [
        migrations.RunPython(modify_permission, reverse_code=migrations.RunPython.noop),
    ]
