# Generated by Django 3.1.14 on 2023-01-06 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_spidercronjob_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('NOT ESPECIFIED', 'Not specified'), ('E-COMMERCE', 'E-commerce'), ('LOGISTICS', 'Logistics'), ('FINANCE', 'Finance'), ('EDUCATIONAL', 'Educational'), ('TECHNOLOGY', 'Technology'), ('OTHER_CATEGORY', 'Other category')], default='OTHER_CATEGORY', help_text="Project's category.", max_length=30),
        ),
    ]
