# Generated by Django 3.1.14 on 2023-01-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_project_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="permission",
            name="permission",
            field=models.CharField(
                choices=[
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                    ("DEVELOPER", "Developer"),
                    ("VIEWER", "Viewer"),
                ],
                default="VIEWER",
                help_text="Permission on this project.",
                max_length=16,
            ),
        ),
    ]
