# Generated by Django 3.1.14 on 2023-03-20 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0024_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "aid",
                    models.AutoField(
                        help_text="A unique integer value identifying this activity.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Activity creation date."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Activity description.", max_length=1000
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project to which the activity corresponds.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the activity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
