# Generated by Django 3.1.14 on 2023-03-21 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_userprofile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
