# Generated by Django 3.1.14 on 2023-03-29 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0024_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "nid",
                    models.AutoField(
                        help_text="A unique integer value identifying each notification",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message",
                    models.CharField(
                        help_text="Notifications message.", max_length=1000
                    ),
                ),
                (
                    "seen",
                    models.BooleanField(
                        default=False, help_text="Whether the notification was seen."
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Notification send date."
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project to which the notifications corresponds.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User whose this notification belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
