# Generated by Django 3.1.14 on 2023-03-02 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="data_expiry_days",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Days before data expires."
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="data_status",
            field=models.CharField(
                choices=[
                    ("PERSISTENT", "Persistent"),
                    ("PENDING", "Pending"),
                ],
                default="PERSISTENT",
                help_text="Data status.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="spider",
            name="data_expiry_days",
            field=models.PositiveSmallIntegerField(
                default=1, help_text="Days before data expires."
            ),
        ),
        migrations.AddField(
            model_name="spider",
            name="data_status",
            field=models.CharField(
                choices=[
                    ("PERSISTENT", "Persistent"),
                    ("PENDING", "Pending"),
                ],
                default="PERSISTENT",
                help_text="Data status.",
                max_length=20,
            ),
        ),
    ]
