# Generated by Django 3.1.14 on 2023-04-11 23:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0026_auto_20230411_0631"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("NOT SPECIFIED", "Not specified"),
                    ("E-COMMERCE", "E-commerce"),
                    ("LOGISTICS", "Logistics"),
                    ("FINANCE", "Finance"),
                    ("EDUCATIONAL", "Educational"),
                    ("TECHNOLOGY", "Technology"),
                    ("OTHER_CATEGORY", "Other category"),
                ],
                default="OTHER_CATEGORY",
                help_text="Project's category.",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "aid",
                    models.AutoField(
                        help_text="A unique integer value identifying this activity.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Activity creation date."
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Activity description.", max_length=1000
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project to which the activity corresponds.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who performed the activity.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
    ]
