# Generated by Django 3.1.14 on 2023-04-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0026_auto_20230411_0631"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderjobenvvar",
            name="masked",
            field=models.BooleanField(
                default=False, help_text="Whether the env variable value is masked."
            ),
        ),
    ]
