# Generated by Django 3.1.14 on 2023-04-18 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_auto_20230411_0631"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderjobenvvar",
            name="project",
            field=models.ForeignKey(
                help_text="Project pid.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="env_vars",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="spiderjobenvvar",
            name="spider",
            field=models.ForeignKey(
                help_text="Spider sid.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="env_vars",
                to="core.spider",
            ),
        ),
    ]
