# Generated by Django 3.1.14 on 2023-07-04 09:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def clean_notifications(apps, schema_editor):
    Notification = apps.get_model("core", "Notification")
    Notification.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0029_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "aid",
                    models.AutoField(
                        help_text="A unique integer value identifying this activity.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date when the activity was performed.",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        help_text="Activity description.", max_length=1000
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.RemoveField(
            model_name="notification",
            name="message",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="project",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="users",
        ),
        migrations.AddField(
            model_name="notification",
            name="seen",
            field=models.BooleanField(
                default=False, help_text="Whether the notification was seen."
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="user",
            field=models.ForeignKey(
                help_text="User that received the notification.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="category",
            field=models.CharField(
                choices=[
                    ("NOT SPECIFIED", "Not specified"),
                    ("E-COMMERCE", "E-commerce"),
                    ("LOGISTICS", "Logistics"),
                    ("FINANCE", "Finance"),
                    ("EDUCATIONAL", "Educational"),
                    ("TECHNOLOGY", "Technology"),
                    ("OTHER_CATEGORY", "Other category"),
                ],
                default="OTHER_CATEGORY",
                help_text="Project's category.",
                max_length=30,
            ),
        ),
        migrations.DeleteModel(
            name="UserNotification",
        ),
        migrations.AddField(
            model_name="activity",
            name="project",
            field=models.ForeignKey(
                help_text="Project where the activity was performed.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="core.project",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                help_text="User who performed the activity.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(clean_notifications),
        migrations.AddField(
            model_name="notification",
            name="activity",
            field=models.ForeignKey(
                help_text="Activity that originated the notification.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="core.activity",
            ),
        ),
    ]
