# Generated by Django 3.1.14 on 2023-07-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='framework',
            field=models.CharField(choices=[('SCRAPY', 'Scrapy'), ('REQUESTS', 'Requests')], default='SCRAPY', help_text="Project's framework.", max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='is_framework_set',
            field=models.BooleanField(default=False, help_text='Whether the framework was set.'),
        ),
    ]
