# Generated by Django 3.1.14 on 2023-07-11 11:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0030_activity"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["name"]},
        ),
    ]
