# Generated by Django 3.1.14 on 2023-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_project_oder_by_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="framework",
            field=models.CharField(
                choices=[("SCRAPY", "Scrapy"), ("REQUESTS", "Requests")],
                default="SCRAPY",
                help_text="Project's framework.",
                max_length=20,
            ),
        ),
    ]
