# Generated by Django 3.1.14 on 2025-07-30 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_mark_existing_jobs_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderjob',
            name='exclude_from_insertion_updates',
            field=models.BooleanField(default=False, help_text='Whether the job should be excluded from further progress updates.'),
        ),
    ]
