# Generated by Django 3.1.14 on 2025-09-26 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_spiderjob_exclude_from_insertion_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('cid', models.AutoField(help_text='A unique integer value identifying this connection.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Connection name.', max_length=255)),
                ('conn_type', models.CharField(choices=[('DATABASE', 'Database'), ('S3', 'AWS S3'), ('FTP', 'FTP'), ('SFTP', 'SFTP'), ('HTTP', 'HTTP'), ('WEBHOOK', 'Webhook')], help_text='Connection type.', max_length=50)),
                ('host', models.CharField(blank=True, help_text='Connection host.', max_length=500)),
                ('port', models.CharField(blank=True, help_text='Connection port.', max_length=10)),
                ('login', models.CharField(blank=True, help_text='Connection login/username.', max_length=500)),
                ('password', models.CharField(blank=True, help_text='Connection password.', max_length=5000)),
                ('extra', models.JSONField(blank=True, default=dict, help_text='Additional connection configuration.')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Connection creation date.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Connection last update date.')),
                ('project', models.ForeignKey(help_text='Project this connection belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='core.project')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'project')},
            },
        ),
        migrations.CreateModel(
            name='AirflowDAG',
            fields=[
                ('did', models.AutoField(help_text='A unique integer value identifying this DAG.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='DAG name.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='DAG description.')),
                ('template', models.CharField(help_text='Template used for this DAG.', max_length=100)),
                ('template_config', models.JSONField(default=dict, help_text='Template configuration parameters.')),
                ('target_schema', models.CharField(blank=True, help_text='Target database schema/collection name.', max_length=500)),
                ('schedule', models.CharField(blank=True, help_text='DAG schedule (cron expression or preset).', max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('DRAFT', 'Draft')], default='DRAFT', help_text='DAG status.', max_length=20)),
                ('dag_id', models.CharField(help_text='Unique DAG identifier in Airflow.', max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='DAG creation date.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='DAG last update date.')),
                ('connection', models.ForeignKey(help_text='Connection this DAG uses.', on_delete=django.db.models.deletion.CASCADE, related_name='airflow_dags', to='core.connection')),
                ('project', models.ForeignKey(help_text='Project this DAG belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='airflow_dags', to='core.project')),
                ('spider', models.ForeignKey(help_text='Spider this DAG is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='airflow_dags', to='core.spider')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
