# Generated by Django 3.1.14 on 2026-04-22 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def create_profiles_for_existing_users(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserProfile = apps.get_model("core", "UserProfile")
    UserProfile.objects.bulk_create([
        UserProfile(user=user) for user in User.objects.all()
    ])


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0038_add_resource_tier_to_spiderjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory_quota', models.PositiveIntegerField(default=6144, help_text='Maximum total memory this user can consume across all running jobs in all their projects.')),
                ('user', models.OneToOneField(help_text='User.', on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_profiles_for_existing_users, migrations.RunPython.noop),
    ]
