# Generated by Django 3.1.14 on 2026-04-28 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0038_add_resource_tier_to_spiderjob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "rid",
                    models.AutoField(
                        help_text="A unique integer value identifying this resource.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("SPIDER_JOB", "Spider Job"),
                            ("PROJECT_DEPLOY", "Project Deploy"),
                        ],
                        help_text="Resource kind.",
                        max_length=32,
                    ),
                ),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROVISIONING", "Provisioning"),
                            ("RUNNING", "Running"),
                            ("STOPPING", "Stopping"),
                            ("TERMINATED", "Terminated"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        help_text="Resource lifecycle phase.",
                        max_length=32,
                    ),
                ),
                (
                    "desired_spec",
                    models.JSONField(
                        default=dict,
                        help_text="Desired resource spec managed by the control plane.",
                    ),
                ),
                (
                    "observed_state",
                    models.JSONField(
                        default=dict,
                        help_text="Last observed state reported by workers/backends.",
                    ),
                ),
                (
                    "external_ref",
                    models.JSONField(
                        default=dict,
                        help_text="References to provider/runtime objects (e.g. job names or IDs).",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Latest reconciliation error message.",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of reconciliation retries for this resource.",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True,
                        editable=False,
                        help_text="Resource creation date.",
                    ),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Resource update date.",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project UUID.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.AddField(
            model_name="deploy",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional control-plane resource for this deploy.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="deploys",
                to="core.resource",
            ),
        ),
        migrations.AddField(
            model_name="spiderjob",
            name="resource",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional control-plane resource for this job.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="spider_jobs",
                to="core.resource",
            ),
        ),
    ]
