# Generated by Django 3.1.14 on 2026-06-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('BUILDING', 'Building'), ('DOWNLOADING', 'Downloading'), ('FAILURE', 'Failure'), ('CANCELED', 'Canceled')], default='BUILDING', help_text='Deploy status.', max_length=12),
        ),
    ]
