# Generated by Django 3.1.14 on 2026-06-23 00:41

from django.db import migrations, models
from django.db.models import Max


def populate_last_modified(apps, schema_editor):
    Project = apps.get_model("core", "Project")
    Spider = apps.get_model("core", "Spider")
    Deploy = apps.get_model("core", "Deploy")
    SpiderJob = apps.get_model("core", "SpiderJob")
    for project in Project.objects.filter(last_modified__isnull=True):
        spider_ids = Spider.objects.filter(project=project).values_list("sid", flat=True)
        last_deploy = Deploy.objects.filter(spiders__in=spider_ids).aggregate(d=Max("created"))["d"]
        last_job = SpiderJob.objects.filter(spider__in=spider_ids).aggregate(j=Max("created"))["j"]
        dates = [d for d in [last_deploy, last_job] if d is not None]
        project.last_modified = max(dates) if dates else project.created
        project.save(update_fields=["last_modified"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_auto_20260623_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='Project creation date.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='last_modified',
            field=models.DateTimeField(help_text='Date of last activity (deploy or job).', null=True),
        ),
        migrations.RunPython(populate_last_modified, migrations.RunPython.noop),
    ]
