# Generated by Django 3.1.14 on 2026-07-15 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_metered_usage_record"),
        ("core", "0041_auto_20260623_0041"),
    ]

    operations = []
