swagger: '2.0'
info:
  title: Bitmaker API v1.0 Documentation
  description: Bitmaker API Swagger Specification
  version: v1
host: 127.0.0.1:8000
schemes:
  - http
basePath: /
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Basic:
    type: basic
security:
  - Basic: []
paths:
  /api/auth/login:
    post:
      operationId: api_auth_login
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/AuthToken'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Token'
      tags:
        - api
    parameters: []
  /api/projects:
    get:
      operationId: api_projects_list
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
        - name: page_size
          in: query
          description: Number of results to return per page.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Project'
      tags:
        - api
    post:
      operationId: api_projects_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Project'
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/Project'
      tags:
        - api
    parameters: []
  /api/projects/{pid}:
    get:
      operationId: api_projects_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Project'
      tags:
        - api
    put:
      operationId: api_projects_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Project'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Project'
      tags:
        - api
    patch:
      operationId: api_projects_partial_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/Project'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Project'
      tags:
        - api
    delete:
      operationId: api_projects_delete
      description: ''
      parameters: []
      responses:
        '204':
          description: ''
      tags:
        - api
    parameters:
      - name: pid
        in: path
        required: true
        type: string
  /api/projects/{pid}/set_related_spiders:
    put:
      operationId: api_projects_set_related_spiders
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SetRelatedSpidersProject'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SetRelatedSpidersProject'
      tags:
        - api
    parameters:
      - name: pid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders:
    get:
      operationId: api_projects_spiders_list
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
        - name: page_size
          in: query
          description: Number of results to return per page.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/Spider'
      tags:
        - api
    parameters:
      - name: pid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}:
    get:
      operationId: api_projects_spiders_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/Spider'
      tags:
        - api
    parameters:
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/cronjobs:
    get:
      operationId: api_projects_spiders_cronjobs_list
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
        - name: page_size
          in: query
          description: Number of results to return per page.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/SpiderCronJob'
      tags:
        - api
    post:
      operationId: api_projects_spiders_cronjobs_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderCronJobCreate'
        - name: async
          in: query
          type: string
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SpiderCronJobCreate'
      tags:
        - api
    parameters:
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/cronjobs/{cjid}:
    get:
      operationId: api_projects_spiders_cronjobs_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderCronJob'
      tags:
        - api
    put:
      operationId: api_projects_spiders_cronjobs_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderCronJob'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderCronJob'
      tags:
        - api
    patch:
      operationId: api_projects_spiders_cronjobs_partial_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderCronJob'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderCronJob'
      tags:
        - api
    parameters:
      - name: cjid
        in: path
        required: true
        type: string
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/cronjobs/{cjid}/stop:
    put:
      operationId: api_projects_spiders_cronjobs_stop
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderCronJob'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderCronJob'
      tags:
        - api
    parameters:
      - name: cjid
        in: path
        required: true
        type: string
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/jobs:
    get:
      operationId: api_projects_spiders_jobs_list
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
        - name: page_size
          in: query
          description: Number of results to return per page.
          required: false
          type: integer
      responses:
        '200':
          description: ''
          schema:
            required:
              - count
              - results
            type: object
            properties:
              count:
                type: integer
              next:
                type: string
                format: uri
                x-nullable: true
              previous:
                type: string
                format: uri
                x-nullable: true
              results:
                type: array
                items:
                  $ref: '#/definitions/SpiderJob'
      tags:
        - api
    post:
      operationId: api_projects_spiders_jobs_create
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderJobCreate'
        - name: async
          in: query
          type: string
      responses:
        '201':
          description: ''
          schema:
            $ref: '#/definitions/SpiderJobCreate'
      tags:
        - api
    parameters:
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/jobs/{jid}:
    get:
      operationId: api_projects_spiders_jobs_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderJob'
      tags:
        - api
    put:
      operationId: api_projects_spiders_jobs_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderJobUpdate'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderJobUpdate'
      tags:
        - api
    patch:
      operationId: api_projects_spiders_jobs_partial_update
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderJob'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderJob'
      tags:
        - api
    parameters:
      - name: jid
        in: path
        required: true
        type: string
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/jobs/{jid}/data:
    get:
      operationId: api_projects_spiders_jobs_data_list
      description: ''
      parameters:
        - name: page
          in: query
          description: A page number within the paginated result set.
          required: false
          type: integer
        - name: page_size
          in: query
          description: Number of results to return per page.
          required: false
          type: integer
      responses:
        '200':
          description: ''
      tags:
        - api
    parameters:
      - name: jid
        in: path
        required: true
        type: string
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/jobs/{jid}/data/{id}:
    get:
      operationId: api_projects_spiders_jobs_data_read
      description: ''
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - api
    parameters:
      - name: id
        in: path
        required: true
        type: string
      - name: jid
        in: path
        required: true
        type: string
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
  /api/projects/{pid}/spiders/{sid}/jobs/{jid}/stop:
    put:
      operationId: api_projects_spiders_jobs_stop
      description: ''
      parameters:
        - name: data
          in: body
          required: true
          schema:
            $ref: '#/definitions/SpiderJob'
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SpiderJob'
      tags:
        - api
    parameters:
      - name: jid
        in: path
        required: true
        type: string
      - name: pid
        in: path
        required: true
        type: string
      - name: sid
        in: path
        required: true
        type: string
definitions:
  AuthToken:
    required:
      - username
      - password
    type: object
    properties:
      username:
        title: Username
        type: string
        minLength: 1
      password:
        title: Password
        type: string
        minLength: 1
  Token:
    required:
      - key
    type: object
    properties:
      key:
        title: Key
        type: string
        maxLength: 40
        minLength: 1
  Project:
    required:
      - name
    type: object
    properties:
      pid:
        title: Pid
        type: string
        format: uuid
        readOnly: true
      name:
        title: Name
        type: string
        maxLength: 1000
        minLength: 1
      token:
        title: Token
        type: string
        readOnly: true
      container_image:
        title: Container image
        type: string
        readOnly: true
  SetRelatedSpidersProject:
    required:
      - spiders_names
    type: object
    properties:
      pid:
        title: Pid
        type: string
        format: uuid
        readOnly: true
      spiders_names:
        type: array
        items:
          type: string
          maxLength: 1000
          minLength: 1
  Spider:
    required:
      - name
      - project
    type: object
    properties:
      sid:
        title: Sid
        type: integer
        readOnly: true
      name:
        title: Name
        type: string
        maxLength: 1000
        minLength: 1
      project:
        title: Project
        type: string
        format: uuid
  SpiderJobArg:
    required:
      - name
      - value
    type: object
    properties:
      name:
        title: Name
        type: string
        maxLength: 1000
        minLength: 1
      value:
        title: Value
        type: string
        maxLength: 1000
        minLength: 1
  SpiderJobEnvVar:
    required:
      - name
      - value
    type: object
    properties:
      name:
        title: Name
        type: string
        maxLength: 1000
        minLength: 1
      value:
        title: Value
        type: string
        maxLength: 1000
        minLength: 1
  SpiderCronJob:
    required:
      - spider
    type: object
    properties:
      cjid:
        title: Cjid
        type: integer
        readOnly: true
      spider:
        title: Spider
        type: integer
      created:
        title: Created
        type: string
        format: date-time
        readOnly: true
      name:
        title: Name
        type: string
        readOnly: true
      cjargs:
        type: array
        items:
          $ref: '#/definitions/SpiderJobArg'
      cjenv_vars:
        type: array
        items:
          $ref: '#/definitions/SpiderJobEnvVar'
      schedule:
        title: Schedule
        type: string
        maxLength: 20
      status:
        title: Status
        type: string
        enum:
          - ACTIVE
          - DISABLED
  SpiderCronJobCreate:
    type: object
    properties:
      cjid:
        title: Cjid
        type: integer
        readOnly: true
      name:
        title: Name
        type: string
        readOnly: true
      cjargs:
        type: array
        items:
          $ref: '#/definitions/SpiderJobArg'
      cjenv_vars:
        type: array
        items:
          $ref: '#/definitions/SpiderJobEnvVar'
      schedule:
        title: Schedule
        type: string
        maxLength: 20
      status:
        title: Status
        type: string
        enum:
          - ACTIVE
          - DISABLED
  SpiderJob:
    required:
      - spider
    type: object
    properties:
      jid:
        title: Jid
        type: integer
        readOnly: true
      spider:
        title: Spider
        type: integer
      created:
        title: Created
        type: string
        format: date-time
        readOnly: true
      name:
        title: Name
        type: string
        readOnly: true
      args:
        type: array
        items:
          $ref: '#/definitions/SpiderJobArg'
      env_vars:
        type: array
        items:
          $ref: '#/definitions/SpiderJobEnvVar'
      job_status:
        title: Job status
        type: string
        readOnly: true
      cronjob:
        title: Cronjob
        type: integer
        x-nullable: true
  SpiderJobCreate:
    type: object
    properties:
      jid:
        title: Jid
        type: integer
        readOnly: true
      name:
        title: Name
        type: string
        readOnly: true
      args:
        type: array
        items:
          $ref: '#/definitions/SpiderJobArg'
      env_vars:
        type: array
        items:
          $ref: '#/definitions/SpiderJobEnvVar'
      job_status:
        title: Job status
        type: string
        readOnly: true
      cronjob:
        title: Cronjob
        type: integer
        x-nullable: true
  SpiderJobUpdate:
    type: object
    properties:
      jid:
        title: Jid
        type: integer
        readOnly: true
      status:
        title: Status
        type: string
        enum:
          - WAITING
          - RUNNING
          - STOPPED
          - INCOMPLETE
          - CANCELLED
          - COMPLETED
          - ERROR
