# frozen_string_literal: true

source "https://rubygems.org"

gem "jekyll"
group :jekyll_plugins do
    # ... other gems
    gem "just-the-docs", "0.4.0.rc4"
    gem "jekyll-tabs"
    gem "kramdown"
end

gem "webrick", "~> 1.7"
