kind: Service
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.QUEUE_PARAMETERS.QUEUE_PLATFORM }}
spec:
  ports:
  - name: broker
    protocol: TCP
    port: {{ .Values.QUEUE_PARAMETERS.QUEUE_PLATFORM_PORT }}
    targetPort: {{ .Values.QUEUE_PARAMETERS.QUEUE_PLATFORM_PORT }}
    nodePort: 0
---
{{- if .Values.local }}
kind: Endpoints
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.QUEUE_PARAMETERS.QUEUE_PLATFORM }}
subsets:
- addresses:
  - ip: {{ .Values.hostIp }}
  ports:
  - name: broker
    port: {{ .Values.QUEUE_PARAMETERS.QUEUE_PLATFORM_PORT }}
{{- end  }}
