kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: queue-items-consumer
spec:
  selector:
    matchLabels:
      app: queue-consumer
  template:
    metadata:
      labels:
        app: queue-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_items']
        envFrom:
        - secretRef:
            name: queue-secrets
        - configMapRef:
            name: queue-config
        {{- if or .Values.CELERY_WORKER_CPU_LIMIT .Values.CELERY_WORKER_MEM_LIMIT }}
        resources:
          {{- if .Values.CELERY_WORKER_CPU_LIMIT }}
          limits:
            cpu: {{ .Values.CELERY_WORKER_CPU_LIMIT }}
          {{- end }}
          {{- if .Values.CELERY_WORKER_MEM_LIMIT }}
          limits:
            memory: {{ .Values.CELERY_WORKER_MEM_LIMIT }}
          {{- end }}
        {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: queue-requests-consumer
spec:
  selector:
    matchLabels:
      app: queue-consumer
  template:
    metadata:
      labels:
        app: queue-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_requests']
        envFrom:
        - secretRef:
            name: queue-secrets
        - configMapRef:
            name: queue-config
        {{- if or .Values.CELERY_WORKER_CPU_LIMIT .Values.CELERY_WORKER_MEM_LIMIT }}
        resources:
          {{- if .Values.CELERY_WORKER_CPU_LIMIT }}
          limits:
            cpu: {{ .Values.CELERY_WORKER_CPU_LIMIT }}
          {{- end }}
          {{- if .Values.CELERY_WORKER_MEM_LIMIT }}
          limits:
            memory: {{ .Values.CELERY_WORKER_MEM_LIMIT }}
          {{- end }}
        {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: queue-stats-consumer
spec:
  selector:
    matchLabels:
      app: queue-consumer
  template:
    metadata:
      labels:
        app: queue-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_stats']
        envFrom:
        - secretRef:
            name: queue-secrets
        - configMapRef:
            name: queue-config
        {{- if or .Values.CELERY_WORKER_CPU_LIMIT .Values.CELERY_WORKER_MEM_LIMIT }}
        resources:
          {{- if .Values.CELERY_WORKER_CPU_LIMIT }}
          limits:
            cpu: {{ .Values.CELERY_WORKER_CPU_LIMIT }}
          {{- end }}
          {{- if .Values.CELERY_WORKER_MEM_LIMIT }}
          limits:
            memory: {{ .Values.CELERY_WORKER_MEM_LIMIT }}
          {{- end }}
        {{- end }}
---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Release.Namespace }}
  name: queue-logs-consumer
spec:
  selector:
    matchLabels:
      app: queue-consumer
  template:
    metadata:
      labels:
        app: queue-consumer
    spec:
      {{- if .Values.imagePullSecrets }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}
      containers:
      - name: consumer
        image: {{ .Values.registryHost }}/estela-consumer:latest
        imagePullPolicy: Always
        command: ['python', 'consumer.py', 'job_logs']
        envFrom:
        - secretRef:
            name: queue-secrets
        - configMapRef:
            name: queue-config
        {{- if or .Values.CELERY_WORKER_CPU_LIMIT .Values.CELERY_WORKER_MEM_LIMIT }}
        resources:
          {{- if .Values.CELERY_WORKER_CPU_LIMIT }}
          limits:
            cpu: {{ .Values.CELERY_WORKER_CPU_LIMIT }}
          {{- end }}
          {{- if .Values.CELERY_WORKER_MEM_LIMIT }}
          limits:
            memory: {{ .Values.CELERY_WORKER_MEM_LIMIT }}
          {{- end }}
        {{- end }}
