name: Lint MR

on:
  pull_request:
    paths:
      - estela-web/**/*
      - .github/workflows/*.yml

env:
  WEB_DIRECTORY: estela-web

jobs:
  lint-web:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: setup node version
        uses: actions/setup-node@v2
        with:
          node-version: 18.0.0
        
      - uses: actions/cache@v4
        id: cache
        with:
          path: $WEB_DIRECTORY/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

      - name: Check Lint
        run: |
          cd $WEB_DIRECTORY
          yarn install
          yarn lint
