# Generated by Django 3.1.1 on 2021-06-30 15:16

from ***REMOVED***.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_spiderjobarg"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderjob",
            name="job_type",
            field=models.CharField(
                choices=[("SINGLE_JOB", "SingleJob"), ("CRON_JOB", "CronJob")],
                default="SINGLE_JOB",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="spiderjob",
            name="schedule",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
