# Generated by Django 3.1.1 on 2021-10-01 00:19

from ***REMOVED***.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_spiderjobenvvar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spiderjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("IN_QUEUE", "In queue"),
                    ("WAITING", "Waiting"),
                    ("RUNNING", "Running"),
                    ("STOPPED", "Stopped"),
                    ("INCOMPLETE", "Incomplete"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("ERROR", "Error"),
                ],
                default="WAITING",
                max_length=16,
            ),
        ),
    ]
