# Generated by Django 3.1.1 on 2021-11-02 06:01

from ***REMOVED***.db import migrations, models
import ***REMOVED***.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_auto_20211001_0019"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spiderjob",
            options={"ordering": ["-created"]},
        ),
        migrations.AlterField(
            model_name="spiderjob",
            name="cronjob",
            field=models.ForeignKey(
                null=True,
                on_delete=***REMOVED***.db.models.deletion.CASCADE,
                related_name="jobs",
                to="core.spidercronjob",
            ),
        ),
        migrations.CreateModel(
            name="SpiderJobTag",
            fields=[
                ("tid", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                (
                    "cronjobs",
                    models.ManyToManyField(
                        blank=True, related_name="ctags", to="core.SpiderCronJob"
                    ),
                ),
                (
                    "jobs",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="core.SpiderJob"
                    ),
                ),
            ],
        ),
    ]
