# Generated by Django 3.1.1 on 2021-12-14 18:46

from ***REMOVED***.conf import settings
from ***REMOVED***.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_removeoldusersfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                through="core.Permission", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
