# Generated by Django 3.1.1 on 2022-06-13 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_deploy"),
    ]

    operations = [
        migrations.AddField(
            model_name="spiderjob",
            name="lifespan",
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name="spiderjob",
            name="total_response_bytes",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "processing_time",
                    models.DurationField(default=datetime.timedelta(0)),
                ),
                ("network_usage", models.PositiveBigIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="core.project",
                    ),
                ),
            ],
        ),
    ]
